### ISSUE TITLE
add support for reading region from ~/.aws/credentials file

### ISSUE THREAD

**Issue by gnowxilef** [aws/aws-sdk-ruby#1028]
similar to the python sdk/cli.

**Comment by awood45** [comment]
Related to #703

**Comment by awood45** [comment]
Current plan is to not support this (the related issue has expanded discussion), but could add this as a feature request and see how much interest there is.

**Comment by awood45** [comment]
We've discussed this a bit further, so here's a bit of an expansion on the discussion.

We're not going to add this to the `~/.aws/credentials` file. The AWS region is not a credential item, and arguably the fact that the CLI loads the region from the credentials file is an implementation bug that they cannot now remove without causing a break for some customers.

However, I can see that, with multiple discussions around this feature request, that there is a demand for something like this. We're exploring the idea of some sort of shared configuration file, and how we could do that without risking breaking behavior for any customers using existing ways to pull in configuration. Not sure what that will look like, exactly, yet (the details of avoiding breaking behavior with this are a bit tricky), but this is a discussion we can have.

Going to close this since we don't intend to support this functionality, but I hear you on the feature request.

**Comment by gnowxilef** [comment]
just to add, i realized i meant to say ~/.aws/config, because i believe that is what the aws cli reads from as well.

**Comment by awood45** [comment]
No worries, I think that's how we're looking at it. There are other problems with supporting everything in the `~/.aws/config` file, but that's part of why we need to discuss on our end how we can support a config file.
