### ISSUE TITLE
Insufficient documentation for :skip_delete

### ISSUE THREAD

**Issue by emirkin** [aws/aws-sdk-ruby#1035]
The docs suggest that `throw :skip_delete` leads to an eventual retry but more details would be desirable.

**Comment by awood45** [comment]
Assuming you're referring to the SQS QueuePoller. Thanks for the report, I'll take a look at it.

**Comment by awood45** [comment]
I'm actually not sure how to re-word this, and I'm open to suggestions.

What the docs currently say is that when the message processing block terminates, the message is deleted automatically. Throwing `:skip_delete` is a way to prevent this behavior if you wish for the message to be returned to the queue.

This does indeed imply that a long running poller will receive the message again, but in the context it feels clear to me.

That said, I'm interested to hear what details you feel are missing so that I can improve the docs.

**Comment by awood45** [comment]
Closing this, but if you have more thoughts on what details are missing I'm happy to take a look.
