### ISSUE TITLE
NameError (uninitialized constant AWS::S3::Resource) while having specified aws-sdk-v1 everywhere

### ISSUE THREAD

**Issue by laetitiamassa** [aws/aws-sdk-ruby#1041]
Hi there,

Thanks for your gem!

I lately had a new error to my apps (which had already been functional for a while) when I created a staging version: while I use aws-sdk-v1 (I rechecked your doc and saw that everything was in place), I still get "NameError (uninitialized constant AWS::S3::Resource)" when I try to upload an image.

What can I do to get it working?

Many thanks in advance.

**Comment by awood45** [comment]
Resource abstractions are a part of the AWS SDK for Ruby V2, which has the `Aws` root module.

If you're using V1 of the SDK, it would have the `AWS` root namespace, but you'd use a top level class like `AWS::S3` for the equivalent behavior.

It sounds like you're creating new code. I'd HIGHLY recommend using V2 of the SDK, as V1 is being imminently deprecated.

**Comment by awood45** [comment]
Going to close this, as it looks like there isn't an issue here.

If you need to use V1 and you'd like to see how to use Amazon S3, the docs are [here](http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3.html).

If you are trying to use V2 and you'd like to see how to use `Aws::S3::Resource`, those docs are [here](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Resource.html).

**Comment by laetitiamassa** [comment]
Thanks for replying.

I haven't created new code (I was just creating a staging app - the production app works with v1 also).

I'm used to aws and stayed with the v1 in order to avoid new required elements.
I've kept using v1 on purpose : 
 my gemlock indicates clearly
"aws-sdk (1.66.0)
      aws-sdk-v1 (= 1.66.0)
    aws-sdk-v1 (1.66.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)"
so I don't get why the expected resources (required in v2 but not in v1) come in my way.

Could you please explain why it would suddenly consider v2 while I've set up the v1 (as I'm used to)?

Thks

**Comment by awood45** [comment]
Resource abstractions are new to V2 - if you're using V1, you'd be using the `AWS::S3` class, rather than `Aws::S3::Resource`.

I'd recommend upgrading to V2, because V1 is on the deprecation path and isn't receiving new features. You can also upgrade to V2 incrementally, rather than all at once. Just add an `aws-sdk-resources` dependency, and you can upgrade incrementally by moving code over to the `Aws` namespace. More advantages of V2 are explained [on the blog](https://aws.amazon.com/blogs/aws/now-available-version-2-of-the-aws-sdk-for-ruby/).
