### ISSUE TITLE
How to stub Resource#exists?

### ISSUE THREAD

**Issue by ktheory** [aws/aws-sdk-ruby#1058]
I'm having trouble stubbing `Aws::S3::Object#exists?` in some tests. Can you help point me in the right direction?

### Setup
```ruby
# In irb console, `irb -raws-sdk`
# Setup stubbing for S3 HeadObject
# NB that 'NoSuchKey' is the error returned by S3's HeadObject call: http://git.io/vzfWF
Aws.config.merge!(stub_responses: true, s3: {stub_responses: {head_object: "NoSuckKey" }})

# Test an object's existence via a bucket
Aws::S3::Object.new(key: 'k', bucket_name: 'b').exists?
```

### Actual behavior

The actual behavior (as of the current version `2.2.10`) is that it raises an `Aws::S3::Errors::NoSuckKey` error.

### Expected behavior:

I'd expect this to return `false` without raising an error, since that's the behavior when not stubbing; and I've stubbed out the API response to be the same as when the object doesn't exist.

I tried to track this down further, but got stuck trying to figure out how the `Aws::S3::Errors::NoSuckKey` gets turned into a `Waiters::Errors::WaiterFailed` that's [rescued by `Resource#exists?`](https://github.com/aws/aws-sdk-ruby/blob/282f9719cf7c6389bee935ab17360e6dd29956d3/aws-sdk-resources/lib/aws-sdk-resources/resource.rb#L135).

Any tips for how to stub `Resource#exists?`

Thanks for all your awesome work. :smile:

**Comment by trevorrowe** [comment]
The bucket exists waiters is checking for a 404 status code, not a specific error code. The HTTP spec requires the the response to a HEAD request not contain a body. Since Amazon S3 normally returns error codes and messages in the body, the HEAD response becomes a simple HTTP 404 not found.

This is where things break down. The client response stubbing interface for errors cheats a little and assumes that the status code is a 400 for all stubbed response. This is largely because we don't have an exhaustive list of errors and their status codes. This could be improved with what we do know, but currently it does not. To make things more difficult, we do have have sufficient information from the status code to disambiguate between NoSuchKey and NoSuchBucket 404 errors. 

That said, you can achieve what you require, but it is small bit of extra work.

```ruby
Aws.config[:s3] = {
  stub_responses: {
    head_object: { status_code: 404, headers: {}, body: '', }
  }
}

Aws::S3::Object.new(key: 'k', bucket_name: 'b').exists?
#=> false
```

Hope this helps.

**Comment by ktheory** [comment]
That works like a charm. Thanks for explaining, @trevorrowe!

**Comment by dominikdarnel** [comment]
It is helpful, but it always returns false, no matter what the key is. How can I make the #exist? depend on the key parameter?

**Comment by rokumatsumoto** [comment]
@dominikdarnel 
You can check out my comment on this [issue](https://github.com/aws/aws-sdk-ruby/issues/1371#issuecomment-626233006)
