### ISSUE TITLE
v1 - EC2 17 character format support?

### ISSUE THREAD

**Issue by jlmoody** [aws/aws-sdk-ruby#1065]
Will v1 of the SDK handle the new instance and reservation ID 17 character format?

**Comment by awood45** [comment]
No - V1 of the SDK is only being changed for major bugs or security vulnerabilities.

However, do note that you can migrate to V2 piecemeal, so if you want to use V2 only for your EC2 operations, even moving over one at a time, you can do that.

For example, if your Gemfile includes V1 like so:
```ruby
gem 'aws-sdk', ~> '1.0'
```
...you can add V2 to your project thusly:
```ruby
gem 'aws-sdk', ~> '1.0'
gem 'aws-sdk-resources'
```
Since the major versions have different namespaces (`AWS` for V1 vs `Aws` for V2), you won't have any naming collisions.

Hope this helps, feel free to reach out if you have more questions about this, or about upgrading.

**Comment by trevorrowe** [comment]
I should add that v1 should support the longer EC2 instance IDs. The SDK does not attempt to validate the length or pattern of instance IDs. You should be able to receive and give the new longer instance IDs without issue.

**Comment by jlmoody** [comment]
Thanks guys!
