### ISSUE TITLE
No API support for DynamoDB reserved capacity operations

### ISSUE THREAD

**Issue by pbfein** [aws/aws-sdk-ruby#1068]
Hi,

There does not appear to be any API equivalent to the following CLI functions:

* dynamodb:DescribeReservedCapacity – returns the reserved capacity purchases that are currently in effect.
* dynamodb:DescribeReservedCapacityOfferings – returns details about the reserved capacity plans that are currently offered by AWS.
* dynamodb:PurchaseReservedCapacityOfferings – performs an actual purchase of reserved capacity.

Can these be added?

**Comment by awood45** [comment]
I'm not seeing this in the AWS CLI either, can you link me to what you're referring to or show me an example?

**Comment by pbfein** [comment]
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/UsingIAMWithDDB.ResourcePermissions.html

DescribeReservedCapacity
DescribeReservedCapacityOfferings

**Comment by awood45** [comment]
For clarity, these are not available in the CLI either. These functions do not currently have an API endpoint and are only available in the console.

If you can explain your use case, I'm happy to pass it on to the DynamoDB team for you.

Closing this since there's nothing to do on the SDK side, but I'll still keep an eye on this and pass on your use case.
