### ISSUE TITLE
Using only a specific component

### ISSUE THREAD

**Issue by hgani** [aws/aws-sdk-ruby#1158]
Hi,

Is it possible to use only a specific component of the gem?

For example, I only need to use the cognito service so including the whole gem doesn't seem efficient. In fact I noticed significant increase in my server's memory usage after using this gem (not sure if it's coincidental).

Thanks

Hendrik

**Comment by trevorrowe** [comment]
The AWS SDK for Ruby uses Ruby's autoload functionality to limit what files/classes are loaded at runtime. If you are only using Aws::EC2, then Aws::S3 code is not loaded.

If you are seeing increased memory usage, there can be multiple causes. If you are using Amazon S3, then you maybe be loading objects into memory instead of streaming them, for example. Also, multiple versions of Ruby have memory leaks in StringIO which is used by the SDK (you may find this goes away with an update of Ruby).

In the future, we are investigating a modularized SDK, where each service ships as a separate gem. We have no formal timeline on when or if this will happen.

**Comment by hgani** [comment]
@trevorrowe Thanks for the quick response and elaborate explanation

I'll check further what's causing the increased memory usage and will follow it up here if I find anything that is of relevance to this gem.
