### ISSUE TITLE
Aws::S3::Errors::BadRequest on certain buckets

### ISSUE THREAD

**Issue by sarboc** [aws/aws-sdk-ruby#1175]
Our team has recently upgraded from v1 of the sdk to v2, and some of our calls which used to return with no errors are now returning `Aws::S3::Errors::BadRequest`. Here is a sample:

```
client = Aws::S3::Client.new(region: 'us-east-1')
client.head_object(bucket: BUCKET, key: KEY)
```

This call will succeed for some of our buckets, but not for others, which leads me to believe that this is a permissions issue. However, we can get a response with no error when using the S3 CLI, the python SDK library, and v1 of the ruby gem, even when doing the same operation on the same bucket where we get an error using the v2 ruby gem.

Can you shed some light on what might have changed under the hood in v2 of the ruby gem that would make a difference in how our calls interact with bucket permissions?

**Comment by trevorrowe** [comment]
I suspect I know what is going on here. A little background first.

When using one of our tools, if you configure your S3 client for "us-east-1", the tool will construct an endpoint like "https://s3.amazonaws.com/....". This is important, because this particular endpoint (and only this endpoint) is global. It relies on DNS to redirect the request to the actual region where the bucket lives.  This means, I could have configured my client for "us-east-1" and actually been redirected to "bucket-name.us-west-2.amazonaws.com".

The reason this matters is because of signature version 4. The v2 SDK uses sigv4 to authenticate the request. Sigv4 signatures contain the region. This means if you configure your client for "us-east-1" but get DNS directed to "us-west-2", the signature is invalid. For most requests, the SDK will correctly detect this error, redirect, cache the actual region and then emit a warning so that the additional hops can be avoided in the future.

In the case of HEAD Object this is not possible today. S3 follows the http rfc that said responses to HEAD requests must not contain a body. For this reason, we have no information from S3 why the request failed.

To verify this, you can try converting the HEAD Object call into a GET Object call. If you enable HTTP wire trace logging you should see multiple requests. If this succeeds, then my suspicion is confirmed.

There are two possible work-arounds:

* Configure your client for the proper region
* Force the SDK to use an older signature version (one that does not need to know the proper region).

To force the SDK to use the older signature version:

```ruby
s3 = Aws::S3::Client.new(signature_version:"s3")
```

To enable wire trace for debugging:

```ruby
s3 = Aws::S3::Client.new(http_wire_trace: true)
```

**Comment by sarboc** [comment]
Thanks for letting me know about the additional client configurations - changing the signature version worked like a charm. And then, of course, configuring the client with the proper bucket was the permanent solution. 

Also, thank you for the excellent explanation of what changed in the authentication!

**Comment by trevorrowe** [comment]
Glad to hear this helped resolve your issue. Please re-open if you run into any further issue.
