### ISSUE TITLE
Cannot assume role provided.

### ISSUE THREAD

**Issue by adityajain21** [aws/aws-sdk-ruby#1218]
When I try to create a new application for deploying through S3, I get this error.
What can be the possible errors?
I created my own service role ARN. It has all permission ("s3:get*" and "s3:list*" ).

**Comment by trevorrowe** [comment]
You didn't provide the error, but I suspect it is because your policy does not permit the proper actions. I believe it should `s3:getObject` instead of `s3:get`. Also, I believe it is `s3:ListBucket`. I'm grabbing these values from here:

http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html
