### ISSUE TITLE
Uninitialize constant AWS

### ISSUE THREAD

**Issue by thebravoman** [aws/aws-sdk-ruby#1247]
After adding a config/initiazers/aws.rb file as shown here:

http://docs.aws.amazon.com/sdkforruby/api/

I get the following error
```
config/initializers/aws.rb:3:in `<top (required)>': uninitialized constant AWS (NameError)
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/railties-4.2.7/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
	from /home/kireto/.rvm/gems/ruby-2.2.2/gems/railties-4.2.7/lib/rails/engine.rb:651:in `load_config_initializer'
```

The content of the file is 

require 'aws-sdk'

AWS.config(
  access_key_id: mykey_id,
  secret_access_key: mykey,
  region: 'us-west-2',
  bucket: mybucket
)
S3_BUCKET =  AWS::S3.new.buckets[ENV['S3_BUCKET']]

In the gem file I have

gem 'aws-sdk', '~> 2'

**Comment by awood45** [comment]
You're writing V1 code with V2 of the gem. The top level namespace in V2 is `Aws` rather than `AWS`, leading to the particular error you saw.

Here is what you should do, as a refactor of the above:

```ruby
require 'aws-sdk'

s3 = Aws::S3::Resource.new(region: "us-west-2")
bucket = s3.bucket(ENV['S3_BUCKET'])
```

Do not hard code your credentials in your code. We have a [variety of ways](http://docs.aws.amazon.com/sdkforruby/api/index.html#Configuration) that you can get credentials into your client, including environment variables, a shared configuration file, and EC2/ECS credential providers. You should use whichever of those approaches is most appropriate for your application setup.

**Comment by trevorrowe** [comment]
To add to @awood45's comment, you can also use version 1 and version 2 of the SDK side by side (in the same application). This allows you to use newer v2 functionality without re-writing existing working code.

See this blog post for an example:
http://ruby.awsblog.com/post/Tx2NJE86FP0HHXX/Announcing-V2-of-the-AWS-SDK-for-Ruby
