### ISSUE TITLE
Generate HTTPS URLs with `public_url` for S3 Objects with a virtual host URL

### ISSUE THREAD

**Issue by sharang-d** [aws/aws-sdk-ruby#1389]
I have a bucket from which I generally fetch objects using the URL generated by `object.public_url(virtual_host: true)`.

I have configured a Cloudfront Distribution to serve objects from this bucket using a custom domain name over both HTTP and HTTPS.

Now, I want `object.public_url(virtual_host: true)` to return me the URL with `https` instead of `http`. I looked through the documentation and the code but I could not find a way to do this using the API.

I suggest that we add an extra option which we can pass to `public_url` so as to generate a URL with `https`. For now, I'm just gonna replace `http` with `https` but I think that this is something which the gem can take care of.

I'd be happy to take a stab at it if you agree that we can have the gem do this.

Thanks.

**Comment by awood45** [comment]
I see where it would be useful for your case, but we think it may involve more than just an extra parameter to allow you to force HTTPS, since this logic is used in other code paths. Can take this on as a feature request.

**Comment by cjyclaire** [comment]
@sharang-d For S3 [Virtual Hosting of Buckets](http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHostingSpecifyBucket), it desgins to address a bucket in a REST API call by using the **HTTP** Host header. That's why scheme is set to [`http`](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/s3/bucket.rb#L75).
Appreciate your feed back on this, may I ask is there any difficulty or blockers for you to use default path style for this?

**Comment by cjyclaire** [comment]
Closing due to inactiveness, yet feel free to reopen with further details or comments : )

**Comment by sharang-d** [comment]
@cjyclaire Sorry for the late response.

> may I ask is there any difficulty or blockers for you not to use virtual-host for https? (path style and DNS are still available)?

I'm sorry but I don't understand what you mean. Is this is setting on the bucket or something like that which you are referring to?

**Comment by cjyclaire** [comment]
@sharang-d No problem at all,  happy to reconsider this as a feature request with more information :).

So the reason why I'm curious and need more information is that, for S3 virtual hosting bucket style, the scheme is set to `http`, it's intentional. I'd like to hear more about why you would want `https` for virtual host style bucket. If you just want `https`, you can try [`:force_path_style`](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#initialize-instance_method).

**Comment by sharang-d** [comment]
@cjyclaire

> I'd like to hear more about why you would want https for virtual host style bucket

I have configured a Cloudfront Distribution to serve objects from this bucket using a custom domain name over both HTTP and HTTPS.
I'm using the result of `object.public_url(virtual_host: true)` to display an image in the browser. When an HTTP URL is used I see the [mixed content warning ](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) telling me that "an insecure content (image URL) is being loaded on a secure page(the app which is on HTTPS)". This is why I need the API call to return an HTTPS version of the URL to me.

>  If you just want https, you can try :force_path_style.

Let me check that and get back to you.

**Comment by sharang-d** [comment]
@cjyclaire

> If you just want https, you can try :force_path_style.

This did not work. I am still getting the http version of the URL.

```ruby
s3_client = Aws::S3::Client.new(region: s3_config[:region], force_path_style: true,
                                credentials: Aws::Credentials.new(s3_config[:access_key_id], s3_config[:secret_access_key]))
s3_key = "SomeKeyWhichExists"
s3obj = Aws::S3::Object.new("BucketName", s3_key, client: s3_client)
s3obj.public_url(virtual_host: true) # Returns the http version
```

**Comment by cjyclaire** [comment]
@sharang-d 
```
s3obj.public_url(virtual_host: true) 
```
This overwrites client config, could you try remove the `:virtual_host` there?

**Comment by sharang-d** [comment]
@cjyclaire 

> This overwrites client config, could you try remove the :virtual_host there?



If I do that the returned URL is not the virtual host URL which I use for hiding the bucket/region details.

```
s3obj.public_url(virtual_host: true)
=> "http://<mysubdomain.mydomain.com>/d8391719aa34feef8192c0faabc10e93"

s3obj.public_url
=> "https://<region>.amazonaws.com/<bucket>/d8391719aa34feef8192c0faabc10e93"
```

I want the former to be returned with https.
I hope you understand my problem/requirement now.

**Comment by cjyclaire** [comment]
@sharang-d I understand that you want `https` with virtual host style, however, as in my first comment, [S3 Bucket VirtualHosting](http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html) has limitations with `:https` scheme:
> When using virtual hosted–style buckets with SSL, the SSL wild card certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic.
> Specifying the bucket for the request by using the HTTP Host header is supported for non-SSL requests and when using the REST API

That's why it's set to `http`, thus I'm curious about your requirement originally, if you still want ':https' with virtual host, I can make this in the feature backlog as an optional parameter. Does that sound good to you? : )

**Comment by sharang-d** [comment]
> I'm curious about your requirement originally

I've answered that above. :)
> I'm using the result of `object.public_url(virtual_host: true)` to display an image in the browser. When an HTTP URL is used I see the [mixed content warning ](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) telling me that "an insecure content (image URL) is being loaded on a secure page(the app which is on HTTPS)". This is why I need the API call to return an HTTPS version of the URL to me.

This plus the fact that I have a valid certificate in place to use the HTTPS version makes me want https always.

 >  I can make this in the feature backlog as an optional parameter. Does that sound good to you? : )

👍

**Comment by albandum** [comment]
Hi, 
Just wondering if that https option has ever been added ? I'm facing the exact same issue. I'm managing the certificate and need https urls, but I can't figure out how to do it correctly.

Thanks !

**Comment by alextwoods** [comment]
@albandum  - We just added support for this in #2485. This change actually makes `public_url` behave consistently with `presigned_url` with `virtual_host` and now defaults to `https`.  For users where https does not work (ie, bucket names containing dot (.) characters), you may set `secure: false` to fallback to using http.
