### ISSUE TITLE
is there a way to filter resources with NOT/missing conditions?

### ISSUE THREAD

**Issue by vbichov** [aws/aws-sdk-ruby#1424]
Filter by resources missing a tag

Simmilar issue described here:
https://forums.aws.amazon.com/thread.jspa?messageID=740190

**Comment by cjyclaire** [comment]
@vbichov Quick question, are you looking for this feature with Ec2 instances in particular? Looks like it's true that the code snippet provided in the forum doesn't work. Since your resource is build upon service APIs, I can reach out to service team for verification and perhaps feature request.

Does that sounds good to you?

**Comment by vbichov** [comment]
Acctually I stumbled on this when trying to filter volumes that aren't tagged.

But yes, it sounds great.

Thank you @cjyclaire

**Comment by cjyclaire** [comment]
Soft updates,  it's true that they don't support this right now, and a feature request has been created in EC2 backlog. So far they support some regex filters:
[Using_Filtering](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html#Filtering_Resources_CLI)
[API_DescribeInstances](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html)

The feature request will be prioritized into implementation queue :)
Appreciate your patience, closing, feel free to reopen with further questions : )
