### ISSUE TITLE
Stub_data not behaving as I would expect

### ISSUE THREAD

**Issue by MMartyn** [aws/aws-sdk-ruby#1456]
I am trying to stub out responses for various interactions within my specs to enable easier testing. My first attempt was to make use of stub_responses, but after playing with that for a bit the only option I have to get the proper responses based off of arguments passed was to keep track of how many times a service was called and make sure the response I wanted for that interaction was at the proper array index on the stubbed responses. 

So I switched to stub_data. I started to utilize my test framework like so `client.stubs(:describe_instances).with(...).returns(client.stub_data(:describe_instances, {...})`. This worked until I hit places where we were actually using resources instead of the client. From my testing I can see that it makes use of `client.describe_instances` however it throws an error `NoMethodError: undefined method `data' for #<Aws::EC2::Types::DescribeInstancesResult` in /aws-sdk-resources/builder_sources.rb:88

I would have expected the stub_data method to provide the exact same thing as the actual response so I am not clear on why that would throw an error.

**Comment by MMartyn** [comment]
No problem here you go:

```
it 'test case' do
  ::Aws::EC2::Client
    .any_instance
    .stubs(:describe_vpcs)
    .with(filters: [{ name: 'tag:Name', values: ['Test'] }])
    .returns(
      ::Aws::EC2::Client.new.stub_data(
        :describe_vpcs,
        vpcs: [
          {
            vpc_id: 'vpc-12345678',
            state: 'available',
            cidr_block: '192.168.0.0/16',
            dhcp_options_id: 'dopt-a1b2c345',
            tags: [
              { key: 'Name', value: 'Test' }
            ],
            instance_tenancy: 'default',
            is_default: false
          }
        ]
      )
    )

  resource = ::Aws::EC2::Resource.new
  resource.vpcs(
    filters: [{ name: 'tag:Name', values: ['Test'] }]
  ).to_a.first # throws error
end
```

**Comment by cjyclaire** [comment]
@MMartyn From your snippet I'm assuming you are trying to stub responses for each instance vpcs and do something with those mocking vpcs resources?

From the error message, looks like the problem is with `#describe_instances`, in your code snippet, it should be at `.any_instance` correct? I don't think SDK have an implementation for this at [`Aws::EC2::Client`](http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html), is this something that you have written?

From your current snippet, generally it looks good in the way how you stub data, yet after the data is stubbed, you are trying to get response from resource instead of the same EC2 client, that could be the problem. It will still make requests.

**Comment by MMartyn** [comment]
@cjyclaire The error for the provided snippet is `NoMethodError: undefined method `data' for #<Aws::EC2::Types::DescribeVpcsResult` but I have also hit this same error stubbing out describe_instances and calling instances on an ec2 resource.

As for the any_instance and stubs methods those are from mocha (https://github.com/freerange/mocha) which allow me to stub those calls out and return a stubbed response. I am using that because if I call describe_vpcs with a different filter I want a different stubbed response.

**Comment by cjyclaire** [comment]
@MMartyn Thanks for the clarifications, ah I see, taking a second look

**Comment by cjyclaire** [comment]
@MMartyn A quick update, I can reproduce this, you could work around this by using the stubbed client making request directly instead of using resource class like:
``` ruby
resp = client.describe_vpcs(
 filters: [{ name: 'tag:Name', values: ['Test'] }]
).to_a.first
```
I'm working on diving deeper to see what causes this issue. Thanks!

**Comment by MMartyn** [comment]
@cjyclaire Thanks for looking into it.

**Comment by cjyclaire** [comment]
@MMartyn So, [`ClientStubs`](http://docs.aws.amazon.com/sdkforruby/api/Aws/ClientStubs.html) lives in `aws-sdk-core` and binds with clients instead of resources. And [`#stub_data`](http://docs.aws.amazon.com/sdkforruby/api/Aws/ClientStubs.html#stub_data-instance_method) is stubbing response data directly instead of an [response object](http://docs.aws.amazon.com/sdkforruby/api/Seahorse/Client/Response.html#data-instance_method). And since SDK build resource object without stubs, when it parses responses, it is assuming a response object, and fetch its [`#data`](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/builder_sources.rb#L61). That's why it will cause error when using stubs with resources. So, working with clients would be the correct solution there.

**Comment by MMartyn** [comment]
Alright, thanks again for looking into it. I think I see what you mean in the code where it handles stub_response differently from stub_data. While in there I noticed that stub_responses can actually take a Proc, so I am going to make use of that.

**Comment by cjyclaire** [comment]
Sounds good, your latest snippet looks good to me. Appreciate your patience on this, closing. Yet feel free to reopen with further comments or questions : )

**Comment by janko-m** [comment]
@MMartyn That's awesome, I had no idea stubs could accept procs, that way I can actually ensure I'm passing the right arguments. I don't see this documented anywhere, so I will try to come up with a PR for that.
