### ISSUE TITLE
Strange region warning

### ISSUE THREAD

**Issue by klippx** [aws/aws-sdk-ruby#1463]
Hello,

I am getting a bit confused by this warning:

```
S3 client configured for "eu-west-1" but the bucket "<redacted>" is in "eu-west-1"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts
```

One the one hand it doesn't make sense to warn when something is X and you expected X, as X == X. But I cannot easily ignore a warning. Any clue what might be going on here?

**Comment by awood45** [comment]
That is strange. Can you provide the wire trace for this, and provide a code snippet that recreates this for you? To turn on wire tracing, add this to client creation:

http_wire_trace: true

This error message is in response to a particular kind of error thrown by the service, so I'd like to gather info.

**Comment by klippx** [comment]
Thanks for the quick reply!

It seems that we are getting this warning when we have an expired token.

```
opening connection to eu-non-production-xxx.s3-eu-west-1.amazonaws.com:443...
opened
starting SSL for eu-non-production-xxx.s3-eu-west-1.amazonaws.com:443...
SSL established
<- "GET /?encoding-type=url&prefix=xxx HTTP/1.1\r\nContent-Type: \r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby2/2.8.10 ruby/2.3.3 x86_64-darwin16\r\nX-Amz-Date: 20170323T122305Z\r\nHost: eu-non-production-xxx.s3-eu-west-1.amazonaws.com\r\nX-Amz-Security-Token: xxx\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=xxx/20170323/eu-west-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=xxx\r\nContent-Length: 0\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "x-amz-bucket-region: eu-west-1\r\n"
-> "x-amz-request-id: B0D3F5FB5BA2AA73\r\n"
-> "x-amz-id-2: xxx\r\n"
-> "Content-Type: application/xml\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Date: Thu, 23 Mar 2017 12:23:05 GMT\r\n"
-> "Connection: close\r\n"
-> "Server: AmazonS3\r\n"
-> "\r\n"
-> "2e8\r\n"
reading 744 bytes...
-> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0>xxx</Token-0><RequestId>B0D3F5FB5BA2AA73</RequestId><HostId>xxx</HostId></Error>"
read 744 bytes
reading 2 bytes...
-> "\r\n"
read 2 bytes
-> "0\r\n"
-> "\r\n"
Conn close
S3 client configured for "eu-west-1" but the bucket "eu-non-production-xxx" is in "eu-west-1"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts
opening connection to eu-non-production-xxx.s3-eu-west-1.amazonaws.com:443...
```

After subsequent login in the warning disappears.

**Comment by cjyclaire** [comment]
@klippx Appreciate your patience and thank you for reporting, do you still see the warnings?

This sounds weird, since `ExpiredToken` should be a 403 error code, and shouldn't cause the [`#get_region_and_retry`](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/lib/aws-sdk-core/plugins/s3_request_signer.rb#L115) that generates the `log_warning`.

Yet I have one suspicion, may I ask do you also have `region` information under the credential profile that have the expired token? The first region in the warning is the region of client configuration, so it's fetched from your profile if you didn't provide a `region` parameter when initializing a client. Then it could be possible that the credentials are refreshed and SDK might still fetching the old region?

If that's the case, I'll need to dig deeper to see if there are potentials bugs.

**Comment by awood45** [comment]
This would be happening because our `wrong_sigv4_region?` check looks at the error code (which expects the `400` you're getting), and then for if the response includes region information, which your error response does.

I think our next steps would be to look at if we can refine that check, or if we can in some other way expose the underlying error to avoid confusion.

To be clear: Your error is the expired token. Which could be a separate issue if you're using a refreshable credentials provider and having these issues.

**Comment by cjyclaire** [comment]
Closing due to inactiveness, feel free to reopen with further details or comments : )
