### ISSUE TITLE
Missing Paginators in Aws::CloudFormation::Client.list_exports

### ISSUE THREAD

**Issue by flyinbutrs** [aws/aws-sdk-ruby#1470]
As the title says, CF client is missing a paginator.

**Comment by cjyclaire** [comment]
Soft ping, I'm adding this across SDKs and PR is in progress :)

**Comment by flyinbutrs** [comment]
Where is the PR? I want to see how it's done so I can submit a PR myself next time, I seem to have a knack for finding missing paginators...

**Comment by cjyclaire** [comment]
@flyinbutrs Really appreciate that!
Sorry but we don't take manual PR fixes, because those `paginator.json` files are automatically generated,  I added those pagination behaviors from root (internally) and is under review. 

However you could easily test and play with paginators by adding them in the [paginator files](https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-core/apis/cloudformation/2010-05-15/paginators-1.json), in this case, you could try testing with:
```
"ListExports": {
      "input_token": "NextToken",
      "output_token": "NextToken",
      "result_key": "Exports"
    },
    "ListImports": {
      "input_token": "NextToken",
      "output_token": "NextToken",
      "result_key": "Imports"
}
```
Note those are hard coded fixes : ) 

Feel free just report pagination missing for any operations, we have enforces pagination rules for all new operations now, yet it could be possible that some old api might still missing paginations : )

**Comment by cjyclaire** [comment]
Closing, the changes are delivered in the latest [release](https://github.com/aws/aws-sdk-ruby/releases/tag/v2.9.0) : )
