### ISSUE TITLE
CloudFormation ValidationError CreateChangeSet changeSetName

### ISSUE THREAD

**Issue by johnathandavis** [aws/aws-sdk-ruby#1511]
Hello,

I'm new to the Ruby SDK (and Ruby), so perhaps I'm looking over something obivous. I'm using the AWS Ruby SDK v2.9.15. My script is running from inside CodeBuild as a post-build step using Ruby version 2.3.1.

I'm calling the CloudFormation CreateChangeSet API using this code  (extra parameters omitted for space):

```
client = Aws::CloudFormation::Client.new(region: region)
  resp = client.create_change_set({
    stack_name: stack_name,
    change_set_name: change_set_name,
    client_token: uuid,
    description: description,
    change_set_type: "UPDATE",
  })
```

And get this error message:
```
[Container] 2017/05/07 00:50:19 An error of type Aws::CloudFormation::Errors::ValidationError happened, message is 1 validation error detected: Value 'stage20170507005018
' at 'changeSetName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
```

I get this error message with any of these values for changeSetName:
- STAGE-2017-05-07-00-50-18
- stage-2017-05-07-00-50-18
- STAGE20170507005018
- stage20170507005018

The only way I can get it to succeed is to remove all numbers. From these docs: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateChangeSet.html
We see that changeSetName is allowed to have a number, it just can't start with it. The regex provided in the error message also backs this up. Am I missing something, or is this a bug / error with the documentation and error message?

**Comment by cjyclaire** [comment]
@johnathandavis Thanks for the info. taking a look.

**Comment by cjyclaire** [comment]
@johnathandavis I tried with different change set name with numbers or '-', and I couldn't reproduce the problem with any of them. Your code snippet looks fine with me (assuming you intentionally omit `template_url` or `template_body` since they are irrelevant to this failure?).

The Error received is a service side validation failure, which is not caused by SDK client side validation. So for further debugging, you could enable  [`http_wire_trace`](http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#initialize-instance_method) to see the http log when making request like:
```
client = Aws::CloudFormation::Client.new(region: region, http_wire_trace: true)
```

Recently our [`#Getting Help`](https://github.com/aws/aws-sdk-ruby#getting-help) section has been updated, feel free to get involved in other channels as well. Such as `Aws Support`, they will also help with trouble shooting with your request IDs : )

If you still feel this is kind of a SDK bug, feel free and further details or debugging log etc.
