### ISSUE TITLE
Ruby consistency: predicate method naming

### ISSUE THREAD

**Issue by eropple** [aws/aws-sdk-ruby#1618]
### Issue description
Ruby tends to (for reasons that I do not agree with, but it's a thing) use the root form of a verb for a predicate method. It would be nice, for consistency, to have methods such as `#exists?` aliased to `#exist?` so as to provide consistency between, say, `File.exist?("/tmp/foo.txt")` and `AWS::S3::Resource.new.bucket(foo).exists?`.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
Most resources (this is an API design question)

**Comment by eropple** [comment]
I understand that it's generated. The generator for Ruby could/probably-should generate aliases to idiomatically present Ruby-conjugated predicate names, is what I'm saying.

**Comment by awood45** [comment]
I hear what you're saying, but unfortunately it's a bit difficult to automatically generate aliases on top of generated/shared resources, and maintain a strong backwards compatibility promise (name collisions are a risk, for example). You're right about the names varying slightly from standard Ruby idioms, but the fix is potentially more damaging than the problem.

Going to close this, let me know if you have any questions.
