### ISSUE TITLE
V2 SDK doesn't work when AWS_SESSION_TOKEN environment variable is set but empty string

### ISSUE THREAD

**Issue by massimocode** [aws/aws-sdk-ruby#1651]
Replication steps
- I am unfortunate enough to be developing in Ruby 
- I use the latest version of the V2 SDK
```
    aws-sdk (2.10.71)
      aws-sdk-resources (= 2.10.71)
    aws-sdk-core (2.10.71)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-resources (2.10.71)
      aws-sdk-core (= 2.10.71)
```
- I use permanent credentials (i.e. where a session token isn't needed) set in my environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
- I have my AWS_SESSION_TOKEN environment variable set to an empty string

Then I get errors saying `The security token included in the request is invalid`

**Comment by cjyclaire** [comment]
@massimocode Hmm weird, I cannot reproduce this in either V3 or V2 SDK with ENV['AWS_SESSION_TOKEN'] set to empty string. 

Can you try not set the token in environment variables if it's not required? Basically, SDK just try fetch "AWS_SESSION_TOKEN" key from ENV, since it presents, it will use its value, which is usually used for assume roles.

**Comment by cjyclaire** [comment]
Closing due to ages, feel free to reopen with further information : )
