### ISSUE TITLE
Aws::Errors::NoSuchEndpointError | Custom endpoint with appended bucket name 

### ISSUE THREAD

**Issue by NorseGaud** [aws/aws-sdk-ruby#1710]
Please fill out the sections below to help us address your issue

### Issue description

I am attempting to call an objects listing but keep receiving NoSuchEndpointError

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3

### Version of Ruby, OS environment
2.5.0, Mac OSX

### Code snippets / steps to reproduce
(XXXX is used to hide website address)
```
Aws.config.update({
                          region: 'vodoriginstorentlka01.g.XXXX.net',
                          credentials: Aws::Credentials.new(ENV['ONEORIGIN_AWS_ACCESS_KEY_ID'], ENV['ONEORIGIN_AWS_SECRET_ACCESS_KEY'])
                      })

s3_client = Aws::S3::Client.new(endpoint: 'https://vodoriginstorentlka01.g.XXXX.net')

Aws::S3::Resource.new(client: s3_client).bucket('mpegstills01').objects({prefix: 'CSNC7402979000090001'})

```

Running these commands gives me

```
Aws::Errors::NoSuchEndpointError: Encountered a `SocketError` while attempting to connect to:
https://mpegstills01.vodoriginstorentlka01.g.XXXX.net/?encoding-type=url&prefix=CSNC7402979000090001
```

Yet, I can make an HTTP GET to vodoriginstorentlka01.g.XXXX.net/mpegstills01?prefix=CSNC7402979000090001 and retrieve a listing of objects.

Does the SDK not support what I'm trying to do? Or is there not a feature yet?

**Comment by cjyclaire** [comment]
@NorseGaud this error for [`#socket_endpoint_error`](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/helpful_socket_errors.rb#L21), your can see the endpoint SDK trying to hit by `s3_client.endpoint`. SDK will make request to the hard code endpoint provided. 

> Yet, I can make an HTTP GET to ...
May I ask is the request `http` instead of `https`? If so, you would need to update the endpoint you provide as well.

**Comment by NorseGaud** [comment]
Thanks for the follow up. Really appreciate the help.

For the HTTP GET, it's using 

```
      url = URI('https://vodoriginstorentlka01.g.comcast.net')
      https = Net::HTTP.new(url.host,url.port)
      https.use_ssl = true
      https.verify_mode = OpenSSL::SSL::VERIFY_NONE # SSL not signed? Don't care!
```

Is there a way to modify `s3_client = Aws::S3::Client.new(endpoint: 'https://vodoriginstorentlka01.g.comcast.net')`, or even s3_client so I can prevent it from using `https://mpegstills01.vodoriginstorentlka01.g.XXXX.net` and instead use `https://vodoriginstorentlka01.g.XXXX.net/mpegstills01` ?

**Comment by NorseGaud** [comment]
Found a spec that seems to indicate that region.endpoint is the format it's definitely setup to create: https://github.com/aws/aws-sdk-ruby/blob/9ea447b7e9e57e27bb7924aca40a5bf0c3265a94/gems/aws-sdk-s3/spec/object/presigned_post_spec.rb

I'll try and play with it and add a feature for what I want. If anyone has any advice for an existing way to achieve this, please let me know! Thanks

**Comment by NorseGaud** [comment]
More review seems to indicate force_path_style: true is a solution, and it is.
I had originally used this in my configuration and it didn't change the endpoint/request url. Attempting it again is working. Here is the working code:

```Aws.config.update({
  region: 'vodoriginstorentlka01.g.XXXX.net',
  force_path_style: true,
  credentials: Aws::Credentials.new(ENV['ONEORIGIN_AWS_ACCESS_KEY_ID'], ENV['ONEORIGIN_AWS_SECRET_ACCESS_KEY'])
})

s3_client = Aws::S3::Client.new(endpoint: 'http://vodoriginstorentlka01.g.XXXX.net')

Aws::S3::Resource.new(client: s3_client).bucket('mpegstills01').objects({prefix: 'CSNC7402979000090001'})


Aws::S3::Resource.new(client: s3_client).bucket('mpegstills01').objects.limit(50).each do |item|
  puts "Name:  #{item.key}"
end```

**Comment by cjyclaire** [comment]
Glad to know that your figured this out. Should have mentioned earlier with the path style and bucket DNS style for S3. It's true that DNS style is by default for S3 in Ruby SDK, and you have the option to set it to force path style as you mentioned. Since you are providing a customized endpoint,   it's not surprising that using path style makes it work : ) and you are on the right path.

Closing, feel free to reopen with further questions or comments : )
