### ISSUE TITLE
S3::Presigner returns links for non-existent items

### ISSUE THREAD

**Issue by beaglebets** [aws/aws-sdk-ruby#1734]
I get pre-signed urls back for objects that don't exist. This seems inconsistent with expectations, since calling `S3::Client.get_object` returns an error when the object does not exist. I would expect the same behavior from the pre-signer. It seems redundant to have to make a call to check if the object exists prior to generating a link. As long as the bucket exists it will return a link. While this makes sense for `:put_object`, I think there should be some sort of validation on the existence of the object.

gem 'aws-sdk' 3.0.1
Ruby 2.4.0 OSX

**Comment by awood45** [comment]
This behavior is intentional. All the presigned URL generator is doing is creating a valid, presigned version of the `:get_object` request. To do what you're asking, we would have to add an additional call to `:head_object`, and that runtime/network overhead is not appropriate for many users.

For example, the presigner method doesn't check for bucket existence either. We will faithfully return a valid presigned request for any set of inputs. I would recommend that:

* If you want to test for object existence before creating a presigned URL, call `:head_object`.
* If you want to test that the `:get_object` call will be successful, have your API make a call to `:get_object` or whichever call you're presigning with the same params before building the URL.

Closing, let me know if you have other follow-up questions or issues with these workarounds.

**Comment by beaglebets** [comment]
Thank you for your prompt response.
