### ISSUE TITLE
Should I use #presigned_url or #presigned_post for direct uploads?

### ISSUE THREAD

**Issue by janko-m** [aws/aws-sdk-ruby#1765]
I've been using `Aws::S3::Object#presigned_post` for generating request parameters for direct client-side uploads to S3. However, I noticed that it doesn't support some things, for instance the checksum.

On the other hand, `Aws::S3::Object#presigned_url(:put)` seems to support more parameters, including `:content_md5`, which is what I want.

So my question is, are there any significant features that `#presigned_post` has that `#presigned_url` doesn't? Does `#presigned_post` exist only because sometimes you're limited to a POST request, e.g. form submit? Should I always use `#presigned_url` if I can?

**Comment by awood45** [comment]
I'd have to explore your use case a bit more, but the main reason `PresignedPost` doesn't have `:content_md5` applied is because you don't have a way to know what the MD5 is when you're presigning the post without a known body.

Can you tell me a bit more about what you're trying to do? If you just want to give permissions for the browser to construct an S3 POST request and want to help it build a post with a checksum, it's possible the Javascript SDK may provide a useful solution, for example.

**Comment by awood45** [comment]
Okay that makes sense, so the use case is to provide a way to allow for more headers, without them being signed headers. I need to do a bit of research on this.

**Comment by janko-m** [comment]
Ok, here are my findings:

When generating `#presigned_url`, one needs to include `:content_md5` option if they want to later include the `Content-MD5` header in the PUT upload request.

When uploading to S3 using `#presigned_post`, the `Content-MD5` header is ignored. This means that, if one wants to use checksums, they need to use `#presigned_url`. 

So, I guess I figured out the answer to my original question: `#presigned_url(:put)` has more features, but `#presigned_post` exists probably for cases when you need to submit the upload request via an HTML form (which only supports the POST verb).
