### ISSUE TITLE
x-amz-meta- headers are not correctly added to X-Amz-SignedHeaders

### ISSUE THREAD

**Issue by maletor** [aws/aws-sdk-ruby#1808]
Per S3 documentation you must add `x-amz-meta-` headers to the `X-Amz-SignedHeaders` signature calculation. Reference: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

Both `host` and `x-amz-meta-` are required. It seems they should be separated with URL encoded semicolon (`%3b`).

When I generate a presigned PUT URL currently I get the `x-amz-meta-` data added as part of the overall query and separated with an ampersand (&). Effectively, I am unable to make a presigned URL for metadata.

```ruby
Aws::S3::Object.new(bucket_name: "bucket", key: SecureRandom.uuid).presigned_url(:put, metadata: { "foo" => "bar" })
```

```
https://bucket.s3.amazonaws.com/4800f41b-db51-43a1-a343-0631daa94d53?x-amz-meta-foo=bar&...
```

When it should be

```
https://bucket.s3.amazonaws.com/4800f41b-db51-43a1-a343-0631daa94d53?X-Amz-SignedHeaders=host%3bx-amz-meta-...
```

**Comment by cjyclaire** [comment]
Thanks for the info! I can reproduce the same SDK pattern you mentioned there, however, I can use the SDK generated presigned url to put an object successfully.

Here is my code snippet:
```ruby
obj = Aws::S3::Object.new(bucket_name: 'bucket', key: 'hello')
url = URI.parse( obj.presigned_url(:put, metadata: {"foo" => "bar"}))

body = "heyhey"
Net::HTTP.start(url.host) {|h| h.send_request("PUT", url.request_uri, body, {"content-type" => ""})}
# => #<Net::HTTPOK 200 OK readbody=true>

obj.get.body.read
=> "heyhey"
```

To help further investigate this, could you let me know if/how the generated url failed for you?(Like usage code snippets? Error message?) Also, could you also let me know the version of SDK used? : )

**Comment by maletor** [comment]
Hi @cjyclaire, 

Yes, of course. This is the error. I apologize for not originally including it.

```xml
<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><HeadersNotSigned>x-amz-meta-foo</HeadersNotSigned><RequestId>CBA5E63921D90B41</RequestId><HostId>+ZvE/GlIZAb09kAx+LUbFEDe472/gQ3glorIHfeSuNXJd3/NZ5jK0KEkI37QCy12teeAV2tVzBA=</HostId></Error>
```

In order to successfully add the user specific metadata, you must send the request with the desired metadata. And in order to have the request authenticate with a presigned URL, the headers must match. So in your test code snippet, add the headers: `x-amz-meta-foo: bar` and see that you will get the above error message back. And if you omit the headers, you will see that `x-amz-meta-foo: bar` is not added to the object.

**Comment by cjyclaire** [comment]
Thanks, apology for forgetting to mention this in my original comment, I can see the metadata is added to the uploaded object:
```
resp = client.get_object(bucket:"bucket",key:"hello")
resp.metadata
# => {"foo"=>"bar"}
```
Then, are you suggesting something like this?
```ruby
Net::HTTP.start(url.host) {|h| h.send_request("PUT", url.request_uri, body, {"content-type" => "",  "x-amz-meta-foo" => "bar"})}
```
I don't think this will sign the `x-amz-meta-foo` header. Because you are making request with a presigned url, I don't think headers sent when making the request can be signed since url is already presigned.

The `metadata` is an parameter option for [`put_object`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#put_object-instance_method) instead of a parameter for presigned url for adding custom headers, are you actually looking for signing a custom header in the presigned url?

**Comment by maletor** [comment]
Hey, you're right. The client/uploader does not need to pass the headers back to S3 when uploading. In fact, doing so results in the XML error message.

What if the payload is variable? Say for something like `x-amz-meta-x-amz-unencrypted-content-length`?

**Comment by awood45** [comment]
If you need to add new headers which require signing at the time of the request, then **pre**signed URLs would not be appropriate for your use case. I'd recommend in such a situation that you perform the necessary signing on the server side. If you must do so on the client side, such as a webpage, you could also do so using the [AWS SDK for Javascript in the Browser](https://aws.amazon.com/sdk-for-browser/), and concepts like CORS to grant narrow permissions to the user directly.

**Comment by maletor** [comment]
@awood45 it's not a new header but a different value for user metadata. We can live without `x-amz-meta-x-amz-unencrypted-content-length` but it'd be nice to offer the client (iOS) be able to set a dynamic value for it.

**Comment by awood45** [comment]
Unfortunately, if the value of a header needs to be signed, you need that value available to you at the time you perform the signing. Otherwise the signature is rendered invalid. In the context you're describing, I think there are 4 options:

1. Use only signed headers which have values available to you at signing time.
2. Push more of what the user is doing back to the server side to make 1 cover the dynamic values.
3. If you're providing a mobile web product, use the browser SDK linked above.
4. If you're providing a mobile app, you may find the [AWS Mobile SDK for iOS](https://aws.amazon.com/documentation/sdk-for-ios/) helpful.

Closing as I think this is answered and there's nothing more we can do here, but happy to answer any follow-up questions.

**Comment by awood45** [comment]
Another possibility might be the [PresignedPost](https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/PresignedPost.html) class. It does have ways to point out metadata headers that will be added at build time as part of a policy, and may help to give you a workaround for this issue.

**Comment by maletor** [comment]
@awood45, our client could pass arguments to our API specifying what it would like for those dynamic values, such as `x-amz-unencrypted-content-length` or `Content-MD5`. I don't think there would be any security issues with that.
