### ISSUE TITLE
NameError Exception: uninitialized constant Aws::AppStream

### ISSUE THREAD

**Issue by richard12511** [aws/aws-sdk-ruby#1818]
Please fill out the sections below to help us address your issue

### Issue description
When trying to initialize an AppStream Client, that's the error I receive. I know the sdk gem is somewhat working because Aws::S3 works, and we use it all the time, but Aws::AppStream throws the above error like the gem is incomplete. 

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk (tried version 2.0 and 2.3)

### Version of Ruby, OS environment
Ruby 2.3.1. Mac OS Sierra 10.12.6

### Code snippets / steps to reproduce
```
credentials = Aws::Credentials.new(ENV.fetch('AWS_ACCESS_KEY_ID'), ENV['AWS_SECRET_ACCESS_KEY'])

Aws.config.update({
    region: ENV.fetch('AWS_REGION'),
    credentials: credentials,
})

S3_BUCKET = Aws::S3::Resource.new.bucket(ENV['AWS_S3_BUCKET'])
APPSTREAM_CLIENT = Aws::AppStream::Client.new(region: 'us-east-1', credentials: credentials)
```

**Comment by cjyclaire** [comment]
If you are using V2 SDK, AppStream is available since [`2.6.31`](https://github.com/aws/aws-sdk-ruby/commit/62fed2b07a4084d260c081ec33982403c18c0998#diff-c6b26dfee22e9267454f77f4ea9b10b9), V3 SDK has AppStream since launch (`aws-sdk-appstream`).

Closing, feel free to reopen with further issues or questions : )
