### ISSUE TITLE
Add info about shared credentials

### ISSUE THREAD

**Issue by Doug-AWS** [aws/aws-sdk-ruby#1902]
Please fill out the sections below to help us address your issue

Got a request from a user for info on using shared credentials, as described in blog post:

https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/

**Comment by srchase** [comment]
@Doug-AWS 

Thanks for opening this issue.

Did the customer have a specific question?

**Comment by srchase** [comment]
@Doug-AWS 

The [configuration documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html#Configuration) describes the way that the SDK automaticaly searches for credentials.

To use a shared credentials file directly, you can do the following:

```
require('aws-sdk-s3')

shared_creds = Aws::SharedCredentials.new(path: 'my_path', profile_name: 'my_profile_name')

s3 = Aws::S3::Client.new(region: 'us-west-2', credentials: shared_creds)
```

The path or profile_name can be omitted to use the respective defaults of '~/.aws/credentials' and 'default'.

Refer to the [SharedCredentials documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SharedCredentials.html).

You can also use the shared_creds to update the global configuration (instead of using them for a specific client):

```
shared_creds = Aws::SharedCredentials.new(path: 'my_path', profile_name: 'my_profile_name')

Aws.config.update(credentials: shared_creds)
```

**Comment by Doug-AWS** [comment]
Sweet, I'll add this to https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html#aws-ruby-sdk-setting-credentials by EOD.

**Comment by Doug-AWS** [comment]
Done.
