### ISSUE TITLE
S3 API put_object fails with IO object

### ISSUE THREAD

**Issue by kreynolds** [aws/aws-sdk-ruby#1927]
Please fill out the sections below to help us address your issue

### Issue description
Using an IO object from IO.pipe causes the following error:

```
ArgumentError: expected params[:body] to be a String or IO object, got value #<IO:fd 8> (class: IO) instead.
```
This error is confusing because that _is_ an `IO` instance.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk-s3 (1.29.0)

### Version of Ruby, OS environment
ruby 2.5.3 on MacOS Mojave

### Code snippets / steps to reproduce
```ruby
IO.pipe do |r, w|
  w << "test"
  w.close
  s3.put_object(
    bucket: 'bucket',
    key: 'object',
    body: r
  )
end
```

**Comment by srchase** [comment]
@kreynolds 

Thanks for opening this issue.

The pipe object needs to be read.  Can you give this a try?

```
IO.pipe do |r, w|
  w << "test"
  w.close
  s3.put_object(
    bucket: 'bucket',
    key: 'object',
    body: r.read
  )
end
```

**Comment by srchase** [comment]
@kreynolds 

See this issue: https://github.com/aws/aws-sdk-ruby/issues/1010

Without a size, the SDK is not able to complete the PUT to S3 (nothing to set the content-length header).

Could you help us with a few more details on your use case so that we might better understand how this might be improved?

**Comment by kreynolds** [comment]
I'm working on a proxy system that manages certain things about how the objects are stored and retrieved in S3. Like other users, there are cases where data is available in an IO object for streaming but its size is unknown.

I switched to the multipart implementation of upload_stream and that works ok. I think my issue here really is that `IO` objects are not supported at all, but the error message and documentation indicates they are. This is probably the last issue you'd see if that were clarified.

**Comment by janko-m** [comment]
@kreynolds `aws-sdk-s3` requires "IO-like" parameters to respond to `#read`, `#rewind`, and `#size`: https://github.com/aws/aws-sdk-ruby/blob/7e38bd1c0dbbe70da8b088160b0aee81b6532b9f/gems/aws-sdk-core/lib/aws-sdk-core/param_validator.rb#L160-L164

Ruby pipes don't respond to `#size`, so this `#io_like?` check fails.

Note that `aws-sdk-core` is probably correct to require `#size`, because otherwise it wouldn't be able to determine the `Content-Length` request header on upload, without first streaming the pipe content to disk (and AWS S3 doesn't support chunked requests).

**Comment by kreynolds** [comment]
I understand what the underlying issue is now, and it makes sense. My recommendation is to change what the _error_ says. Reading it, it looks like nonsense:

```
expected params[:body] to be a String or IO object, got value #<IO:fd 8> (class: IO) instead
```

It should be clear that it needs an object that response to read/rewind/size, not an IO object. This Issue wouldn't exist if the error were clear :)
