### ISSUE TITLE
Feature request: adding content checksum as object metadata

### ISSUE THREAD

**Issue by hejaan** [aws/aws-sdk-ruby#1948]
### Issue description
ContentMD5 isn't stored as metadata on the object in S3. As the ETag returned by S3 is not guaranteed to be the MD5 checksum of the entire object( notably for multipart uploads ), the ETag might be different when downloading.

I could explicitly calculate an MD5 or SHA256 checksum for the file and save it as part of the object metadata, but would you consider adding such function as a built-in option?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
'aws-sdk-s3'

### Version of Ruby, OS environment
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
CentOS Linux release 7.6.1810 (Core)

**Comment by hrjaan** [comment]
A similar reference to the problem is located at - https://github.com/fluent/fluent-plugin-s3/issues/260

**Comment by srchase** [comment]
@hrjaan 

Thanks for submitting this feature request.

Others that are interested in seeing this feature can chime in on this issue.

**Comment by mullermp** [comment]
Sorry for the late response to this (this issue predates my tenure on the project). So taking a look into this, it seems metadata can only be set on [`create_multipart_upload`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#create_multipart_upload-instance_method) and not on [`upload_part`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#upload_part-instance_method) or [`complete_multipart_upload`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#complete_multipart_upload-instance_method). Since `create_multipart_upload` does not take in a file or body, there's no way to implement this as a client plugin. I think it's possible to add functionality to [`Object#upload_file`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#upload_file-instance_method) to take an option that reads the file, calculates the md5, and sets it to the metadata before splitting into parts and uploading. The downside of this is that, because the parts are unordered and only read when `upload_part` is called, the file must be read a total of two times. Because of that, we would need to make this an option that defaults to false.
