### ISSUE TITLE
Aws::SSM::Client `parameter_filters` pagination issue

### ISSUE THREAD

**Issue by sammilechman** [aws/aws-sdk-ruby#2012]
### Issue description
I'm seeing an issue using `describe_parameters` method. Using the `parameter_filters` as shown here:
```
  client = Aws::SSM::Client.new

  client.describe_parameters(
    parameter_filters: [{
      key: 'Name',
      option: 'BeginsWith',
      values: ['/my_filter/foobaz']
    }],
  )
```
I see a result like this:
```
#<struct Aws::SSM::Types::DescribeParametersResult parameters=[],
next_token="next_token_foobar">
```
Using the `next_token` returned, I can make another request:
```
  client.describe_parameters(
    parameter_filters: [{
      key: 'Name',
      option: 'BeginsWith',
      values: ['/my_filter/foobaz']
    }],
  next_token: "next_token_foobar"
  )
```
Now I see the result I was looking for:
```
#<struct Aws::SSM::Types::DescribeParametersResult
parameters=
[#<struct Aws::SSM::Types::ParameterMetadata
name="/my_filter/foobaz",
type="SecureString",
...
```
Is this a bug in the SSM client? Since there's only one result that meets the criteria of the filter, shouldn't that be returned by the first `describe_parameters` call, without the need for a `next_token`?

Thanks for any help or advice you can provide.

### Gem name
```
# Gemfile
gem 'aws-sdk', '~> 3.0.1'

# Gemfile.lock
    aws-sdk-ssm (1.34.0)
      aws-sdk-core (~> 3, >= 3.39.0)
      aws-sigv4 (~> 1.0)
```

### Version of Ruby
```
ruby 2.5.0
```

**Comment by cjyclaire** [comment]
Hmmm I can not reproduce this when only single result is returned (always returned in the first page), from SDK side, we are parsing response from server and we didn't do customizations in this case. 

Does this happens every time for you? might trying set `:http_wire_trace` at the client to get the wire trace?

**Comment by sammilechman** [comment]
@cjyclaire thanks for taking a look - yes, this happens consistently for me. Would your result be returned on the second page in the absence of a filter? That's the way I can surface this behavior.

My working theory is the filter is being applied _after_ the pagination, so that the result which would be on the second page without a filter, is still on the second page with a filter.

**Comment by sammilechman** [comment]
I'll look into `:http_wire_trace` and post here

**Comment by sammilechman** [comment]
This looks like an API bug, and not something that could be fixed here.

**Comment by skolsuper** [comment]
Did you find a resolution to this?  I think I have a similar bug, when searching for a prefix that does not exist I get pages and pages of empty arrays and then a rate limit exceeded error

**Comment by mullermp** [comment]
I believe this to be intended, so that a response can be given to the client quickly. You can use the `.next_page` method to get the next API response using the next token. The SDK should provide appropriate backoff and a retry mechanism.

I dug up a section of the AWS API Standards in our internal documentation with regards to latency:

> A filtering API with very specific filter criteria may require reading the customer's entire data set to find any results. Attempting to fill a target page size for a very large data set could incur an unpredictable amount of latency and require an unpredictable amount of resources (for both the client and server). Services MUST return a truncated or empty response with a relevant NextToken when the service specific threshold is exceeded for constructing a response (e.g., maximum execution time, maximum number of records scanned, maximum payload size, etc).

**Comment by skolsuper** [comment]
Hi @mullermp, thanks for the quick response.  Sounds reasonable about the API but it does seem a bit overkill for parameter store which is limited to 10k parameters total IIRC.  I've opened a support request because this has caused our deployment process to change from taking ~4mins to >30mins every time, starting in the last week.  But anyway this is not an SDK issue so I only mention it to share a bit of context.

> The SDK should provide appropriate backoff and a retry mechanism.

I used the [recommended](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/PageableResponse.html) method to consume the paginated results, the `each` method on `PageableResponse`.  It reliably ends up throwing a RateLimitExceeded error without the `sleep 1` in the block:

```ruby
  params = []
  ssm_client.describe_parameters(
    parameter_filters: [
      { key: 'Name', option: 'BeginsWith', values: [path] }
    ],
    max_results: 50
  ).each do |response|
    params += response.parameters.map do |param|
      name = param.name.split('/').last
      { name: name, value_from: param.name }
    end
    sleep 1
  end
```

I agree it was surprising that rate-limiting and retries were not transparently handled here.

**Comment by mullermp** [comment]
Are you configuring a particular retry strategy? Here is the [related code and options](https://github.com/aws/aws-sdk-ruby/blob/e3bd3f3be4d318351a7db3e6539c181f66e701e9/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L40-L154).

What is the exact error you are seeing? Is it really called `RateLimitExceeded`? I don't see that in the [SSM API](https://github.com/aws/aws-sdk-ruby/blob/version-3/apis/ssm/2014-11-06/api-2.json). If it's missing, it should be added and it should be marked as "retryable". If you're using the legacy retry methods (default) the error should have been listed in this [hand managed list of retryable errors](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retries/error_inspector.rb).

**Comment by skolsuper** [comment]
> Are you configuring a particular retry strategy? Here is the [related code and options](https://github.com/aws/aws-sdk-ruby/blob/e3bd3f3be4d318351a7db3e6539c181f66e701e9/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L40-L154).
> 
> What is the exact error you are seeing? Is it really called `RateLimitExceeded`? I don't see that in the [SSM API](https://github.com/aws/aws-sdk-ruby/blob/version-3/apis/ssm/2014-11-06/api-2.json). If it's missing, it should be added and it should be marked as "retryable". If you're using the legacy retry methods (default) the error should have been listed in this [hand managed list of retryable errors](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retries/error_inspector.rb).

Apologies for being imprecise, the exact error thrown is a `Aws::SSM::Errors::ThrottlingException`.

I did not configure retry strategy at all.  The problem here is not so much that the call is failing, but that it's succeeding so much more slowly.  AWS support has recommended we pay for increased throughput, which is OK I guess, but it sucks a bit to have to pay for all these empty pages that were just recently added for no apparent benefit to us 😅

**Comment by mullermp** [comment]
I personally don't think it's fair for you to pay for more throughput on empty pages. I would push on the support team for the service team to investigate the issue.

**Comment by skolsuper** [comment]
Thanks @mullermp, I did this and the support team requested more info so they could investigate. While getting that info for them, I found I will have to eat my words.  The slowdown was due to another issue with our code slightly downstream of this, the empty pages have probably been there all along.  Thanks so much for your help on this issue anyway, sorry to waste your time 🙏
