### ISSUE TITLE
[MediaStore] Chunked Transfer Coding does not work

### ISSUE THREAD

**Issue by kuu** [aws/aws-sdk-ruby#2067]
### Issue description

HTTP 1.1 Chunked Transfer Coding does not get enabled when calling MediaStoreData.PutObject

### Gem name and its version

aws-sdk-3.0.1

### Version of Ruby, OS environment

ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]

### Code snippets / steps to reproduce

```ruby
require 'aws-sdk'

client = Aws::MediaStoreData::Client.new({
  endpoint: SERVICE_ENDPOINT,
  access_key_id: ACCESS_KEY_ID,
  secret_access_key: SECRET_ACCESS_KEY
})

def upload(filePath, mimeType, targetPath)
  File.open(filePath) {|f|
    client.put_object({
      body: f,
      path: targetPath,
      content_type: mimeType,
      upload_availability: "STREAMING"
    })
  }
end
```

Steps to repro:
* Send a 10MB file to MediaStore container with the above code
* Inspect the HTTP request

Expected Behavior:
* "Transfer-Encoding: chunked" is added to the request header
* The request body is divided into multiple chunks

Actual Behavior:
* No "Transfer-Encoding: chunked"
* "Content-Length" is added to the request header
* The request body is a single chunk

**Comment by cjyclaire** [comment]
`Transfer-Encoding` and related trait are [supported](https://github.com/aws/aws-sdk-ruby/pull/2041) since core gem version [`3.52.0`](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/CHANGELOG.md#3520-2019-05-14) and at `aws-sdk-medialive` [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-mediastore/lib/aws-sdk-mediastore/client.rb#L59) since `1.15.0`.

Currently,`Transfer-Encoding` header will be populated when `v4-unsigned-body` is marked for the streaming operation, not requiring length and when the body size is not available. MediaStore's API model haven't been updated to echo those markers yet, so SDK is not enabled with the behavior. Once service side updates their models, SDK will pick up the behavior automatically.

**Comment by kuu** [comment]
Thanks @cjyclaire for the comment.
Sorry, I still don't understand why the `Transfer-Encoding` header was not added with my code.
Even though some updates are still needed on service side, at least the request header should be added by the SDK, right?

I checked the versions of the installed gems which look good:
```
$ gem list
...
aws-sdk-core (3.54.2)
aws-sdk-medialive (1.33.0)
aws-sdk-mediastore (1.15.0)
aws-sdk-mediastoredata (1.15.0)
```

Can you guide me how I can change my code to fulfill the conditions you stated?

> `Transfer-Encoding` header will be populated when `v4-unsigned-body` is marked for the streaming operation, not requiring length and when the body size is not available.

**Comment by cjyclaire** [comment]
Sorry for the confusion, I'm suggesting [service model](https://github.com/aws/aws-sdk-ruby/blob/master/apis/mediastore/2017-09-01/api-2.json) (provided by them) used in SDK, not server side behavior, is missing those required updates.

**Comment by kuu** [comment]
Thanks @cjyclaire for the comment.
Sorry, I'm still getting confused...

I can see the JSON file for the MediaStoreData.PutObject is declared [here](https://github.com/aws/aws-sdk-ruby/blob/master/apis/mediastore-data/2017-09-01/api-2.json#L71-L84).

Do you mean `Transfer-Encoding: chunked` will be populated if I modify this file and rebuild the SDK?

**Comment by kuu** [comment]
@cjyclaire Just to confirm,
Currently, MediaStoreData.PutObject in ruby sdk does not support `Transfer-Encoding` and we need to wait for updates on the service model.
Is my understanding correct?

**Comment by cjyclaire** [comment]
@kuu apologies for the delay, correct, I'll ping the thread once their model has been updated!

**Comment by mullermp** [comment]
It seems like this issue was dropped. Is this still a problem? I see that the `authtype` is provided in [MediaStoreData PutObject](https://github.com/aws/aws-sdk-ruby/blob/master/apis/mediastore-data/2017-09-01/api-2.json#L83) but I'm not sure where the service team would need to add `authtype` in [MediaStore api](https://github.com/aws/aws-sdk-ruby/blob/master/apis/mediastore/2017-09-01/api-2.json).

**Comment by mullermp** [comment]
I think that this was a bug in the SDK. It looks like that anything that responds to size will pass param validation, and when going to the plugin, checking `#size` will not fail and then the header was never added. The plugin expected `#size` to fail some times. I removed the restriction of checking for `respond_to?(:size)` in the param validator, so that actual IO objects can be passed in, and then those IO objects may not respond to size, triggering the plugin correctly.
