### ISSUE TITLE
Breaking option on S3 bucket.objects

### ISSUE THREAD

**Issue by haotianw465** [aws/aws-sdk-ruby#2198]
We recently upgrade the aws-sdk-ruby v2 dependencies from

```ruby
aws-sdk (2.11.229)
aws-sdk-resources (= 2.11.229)
aws-sdk-core (2.11.229)
```

to

```ruby
aws-sdk (2.11.418)
aws-sdk-resources (= 2.11.418)
aws-sdk-core (2.11.418)
```

And one of our script broke after the upgrade

```ruby
                bucket.objects(:marker => start_key)
                            .select  { |i| i.key =~ /#{@@test_marker}$/ }
                            .collect { |i| Model::TestMarker.for_key(i.key) }
```

with following error:

```ruby
ArgumentError: unexpected value at params[:marker]
```

After checking API reference doc I'm able to fix it after I change the code to 

```ruby
bucket.objects(:start_after => start_key)
```

I checked the change log but couldn't find any useful information. Is this change expected?

Ruby version: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`

**Comment by mullermp** [comment]
Yes -- the resource model API was updated to use ListObjectsV2 rather than V1 about 2 months ago (https://github.com/aws/aws-sdk-ruby/commit/e8cec3e34f0447d35bea67c937079795a6acbfd9). 

V1 Docs (has `marker`) https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#list_objects-instance_method

V2 Docs (no `marker`) https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#list_objects_v2-instance_method

V2 should be backwards compatible with V1. What is your use case for using the marker/pagination in the resource model?

**Comment by haotianw465** [comment]
I am not the original author for this code snippet but from my reading the bucket contains a lot of objects. It might be more efficient when we can have some filtering on server side.

It looks like the option `marker` in V1 is renamed to `start_after` in V2 so it is not backward compatible, which makes `bucket.objects` resource API broken for some users, although I don't know if using `marker` in this API is typical or not. Just want to raise awareness on potential user impact.

**Comment by mullermp** [comment]
I don't think it's typical to use. IIRC V1 pagination was not proper and V2 fixed that, though both APIs list objects the same way. To help do filtering server side, you can check for `prefix`. I'm sorry that it broke you. I'm glad it's fixed as is. Going to close this issue.
