### ISSUE TITLE
Notification to Upgrade to AWS SDK for Ruby V3

### ISSUE THREAD

**Issue by swt2c** [aws/aws-sdk-ruby#2261]
I received an email / notification from AWS stating "One or more applications using your AWS account is using AWS SDK for Ruby version 2. We encourage you to upgrade to AWS SDK for Ruby V3[1], a modular version with a separate module (a.k.a gem) for each AWS service, to take advantage of the latest features. Existing applications that depend on V2 will continue to function."

How did you determine that my account is using AWS SDK for Ruby version 2?  Can you be more specific about where it is being used?  I'm not aware that I'm using AWS SDK for Ruby at all.

**Comment by nberthenet** [comment]
I received the same email and I don't understand why?
Could you explain us how to find which application use AWS SDK for Ruby?

**Comment by alextwoods** [comment]
Applications that use AWS services typically use an SDK such as AWS SDK for Ruby, and AWS records the language and versions of the AWS SDKs that were used to make those requests. These could be custom applications your organization builds and maintains; or 3rd party applications, libraries or tools that use the AWS SDK for Ruby. We record details at the request level, and do not identify the application, library or tool that was used to make the request. Please audit the applications that use the account for which you received the notification to find the one that made the requests. If you find that you aren't directly depending on the AWS SDK for Ruby, then there is no action for you to take. If you find that you are indirectly depending on the AWS SDK for Ruby, please either upgrade that dependency or contact the owner of that dependency, otherwise there is no action for you to take.
 
Note that we do not record any personal information, such as usernames or email addresses or sensitive project-level information. For full details on the values recorded, please see our public documentation on the [user agent string](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/plugins/user_agent.rb).
