### ISSUE TITLE
Aws::S3::Object#initiate_multipart_upload improperly stubs

### ISSUE THREAD

**Issue by TrevorHinesley** [aws/aws-sdk-ruby#2309]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
`Aws::S3::Object#initiate_multipart_upload` returns a `MultipartUpload` that does not honor the stubbed `create_multipart_upload` response underneath.

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sdk-s3` v `1.30.1`

**Version of Ruby, OS environment**
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]

**To Reproduce (observed behavior)**
```
Aws.config[:s3] = {
  stub_responses: {
    create_multipart_upload: {
      bucket: bucket_name,
      key: key,
      upload_id: upload_id
    },
  },
}

client = Aws::S3::Client.new(
  access_key_id: access_key,
  secret_access_key: secret_key,
  region: "us-east-1",
)
bucket =  Aws::S3::Bucket.new(
  name: other_bucket_name, # Something other than what was stubbed
  client: client
)
multipart_upload = bucket.object(other_key).initiate_multipart_upload # other_key = something other than what was stubbed

puts multipart_upload.id # == upload_id
puts multipart_upload.object_key # == other_key
puts multipart_upload.bucket_name # == other_bucket_name
```

**Expected behavior**
The last three lines of the above examples should print:

```
puts multipart_upload.id # == upload_id
puts multipart_upload.object_key # == key
puts multipart_upload.bucket_name # == bucket_name
```

[The problem is here](https://github.com/aws/aws-sdk-ruby/blob/3a68254ca3841441e6d5abb4a44b763c568d56e2/gems/aws-sdk-s3/lib/aws-sdk-s3/object.rb#L924). The `MultipartUpload` is having everything except its ID set with instance variables, rather than what was stubbed in the `create_multipart_upload` response.

**Comment by alextwoods** [comment]
This is a bit of a confusing interaction between client stubbing and the Resource objects.  The [Object#initiaite_multipart_upload](https://github.com/aws/aws-sdk-ruby/blob/3a68254ca3841441e6d5abb4a44b763c568d56e2/gems/aws-sdk-s3/lib/aws-sdk-s3/object.rb#L924) is code generated from the [service's resource definition](https://github.com/aws/aws-sdk-ruby/blob/master/apis/s3/2006-03-01/resources-1.json#L897).   Since this is an operation on a Bucket and Object where the bucket and key have been explicitly set already, if we get something different back in the response, I'd lean towards it being an error, if anything.

In the client stubbing you can pass a Proc (see the Dynamic Stubbing section of the[ Client Stubbing docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ClientStubs.html#stub_data-instance_method)) so depending on your use case / test you could have that proc either return bucket_name/key from the parameters or raise an exception of the operation was called with unexpected parameters.  Something like:

```ruby
# To raise an error on unexpected calls
Aws.config[:s3] = {
  stub_responses: {
    create_multipart_upload: -> (context) {
      if context.params[:bucket] != 'bucket_name'
        raise 'Stubbing called with unexpected arguments!'
      end
      {
        bucket: 'bucket_name',
        key: 'key',
        upload_id: 'upload_id'
      }
    },
  },
}

# To dynamically return based on the params
Aws.config[:s3] = {
  stub_responses: {
    create_multipart_upload: -> (context) {
      {
        bucket: context.params[:bucket],
        key: context.params[:key],
        upload_id: 'upload_id'
      }
    },
  },
}
```

I do think there is an opportunity for us to provide a more powerful DSL for stubbing responses, but I don't think that we should have S3 update their resource model to account for our stubbing.

**Comment by TrevorHinesley** [comment]
@alextwoods I definitely understand where you're coming from.

However, it's a bit of a code smell, or at least a fragile pattern, if stubbing an underlying service call does not affect the output of the relying method intuitively. For instance, in this case, intuitively (after all, the guts rely on `#create_multipart_upload` underneath, which implies tight coupling) it *should* affect the response.

I also don't believe S3 core needs to update their resource model, but I do believe the Ruby gem should either only have standard methods, or the dependent methods underneath should influence the output intuitively.

**Comment by alextwoods** [comment]
@TrevorHinesley  - sorry for the slow response on this, we were discussing internally.   We'd be happy to accept a tested PR that updates the [resource model ](https://github.com/aws/aws-sdk-ruby/blob/master/apis/s3/2006-03-01/resources-1.json#L897) that generates that code (generation can be done with `rake build:aws-sdk-s3`) and we'll then work to get that change merged upstream.
