### ISSUE TITLE
list_tags_for_resource for Managed Instance does not return the list of tags

### ISSUE THREAD

**Issue by parmouraly** [aws/aws-sdk-ruby#2312]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Invoking 
```
response = client.list_tags_for_resource(
    resource_type: "ManagedInstance",
    resource_id: "mi-1234567890",
  )
```

Returns:
```
{:tag_list=>[{:key=>"[FILTERED]", :value=>"[FILTERED]"}]}
```
which does not include the instance tags.

Invoking the same exact API call from AWS CLI returns my list of tags as I expected:

```
{
    "TagList": [
        {
            "Key": "ImageUrl",
            "Value": "XYZ"
        }
    ]
}
```

**Gem name**

```
aws-sdk-ssm (1.77.0)
aws-sdk-core (3.96.0)
```

**Version of Ruby, OS environment**
`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]`

**To Reproduce (observed behavior)**
Invoking 
```
response = client.list_tags_for_resource(
    resource_type: "ManagedInstance",
    resource_id: "mi-1234567890",
  )
```

**Expected behavior**
Return the tags of the ManagedInstance

**Additional context**
I am thinking maybe this is a "feature" to protect sensitive data, however I have not found a flag or any way for me to actually retrieve the tags. I expect/hope there is a way to get the tags and I haven't found it, otherwise the method should not exist in the first place.

**Comment by mullermp** [comment]
related to https://github.com/aws/aws-sdk-ruby/issues/2105

**Comment by parmouraly** [comment]
Hi, is anyone looking at this?

**Comment by mullermp** [comment]
I started a branch for this but I haven't had time to work on it because of competing priorities. We need to make two changes 1) sensitive data should be per service, and 2) an option to disable sensitive information (default to false). For now, you can use `http_wire_trace: true` as a client option or in the console pass the `-v` flag if you want to see the raw wire traces which do not contain filtered information. CLI does not do anything of the sort.

**Comment by parmouraly** [comment]
Cool thanks for the update @mullermp 
I have a workaround atm, shelling out to the CLI from ruby so not a problem. 
Was just wondering if there was any more graceful workaround involving the ruby API.
Unfortunately using `http_wire_trace` messes up with my other calls using the client, so it's not convenient for me. CLI works fine.

**Comment by mullermp** [comment]
Hey @parmouraly, check out the changes on https://github.com/aws/aws-sdk-ruby/pull/234. It should be released tomorrow (if all goes well)! If you are using the latest aws-sdk-core and service gem, sensitive params should be generated based on request/response types rather than a big list. If a type is filtered and you don't want it to be, you can create a logger instance and configure it off.
