### ISSUE TITLE
Can't create ipv6 routes with the Resource model

### ISSUE THREAD

**Issue by fdr** [aws/aws-sdk-ruby#2324]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
 
**Describe the bug**

Looks similar to https://github.com/aws/aws-sdk-ruby/issues/1630. You can't create ipv6 routing table entries. Observe.

Fine, great:

```
rt.create_route(destination_cidr_block: '0.0.0.0/0',  gateway_id: 'igw-')
=> #<Aws::EC2::Route:0x0000000005bdfbf0
...
```

Not fine, bad:

```
rt.create_route(destination_ipv_6_cidr_block: "::/0",  gateway_id: 'igw-')
ArgumentError: missing required option :destination_cidr_block
```

Workaround:

```
rt.client.create_route(route_table_id: rt.id,  destination_ipv_6_cidr_block: "::/0",  gateway_id: 'igw-')                               
=> #<struct Aws::EC2::Types::CreateRouteResult return=true>
```
**Version of Ruby, OS environment**
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

**Comment by mullermp** [comment]
Last I looked at this issue, it can't be fixed because of the limitations of Resource models. I highly recommend that you use the client API instead.

This response sums up the larger problem: https://github.com/aws/aws-sdk-ruby/issues/1630#issuecomment-450205397

Here are the identifiers - https://github.com/aws/aws-sdk-ruby/blob/master/apis/ec2/2016-11-15/resources-1.json#L1660-L1664

With the resource model, it's not possible to use identifiers conditionally.
