### ISSUE TITLE
Installing aws-sdk gems takes extremely long

### ISSUE THREAD

**Issue by alejomongua** [aws/aws-sdk-ruby#2377]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
gem install aws-sdk takes extremely long

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
aws-sdk

**Version of Ruby, OS environment**
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**To Reproduce (observed behavior)**
Create a new AWS EC2 instance with Ubuntu Server 18.04
Install ruby with:
    sudo apt install ruby
Install the aws-sdk gem with:
    sudo gem install -V aws-sdk

**Expected behavior**
It should install in less than 10 minutes

**Additional context**
Adding the -V option for verbosity, I can see it does a lot of requests to api.rubygems.com. It takes more than an hour and it have not finished yet to install, it only goes on and on and on...

**Comment by mullermp** [comment]
You're correct that it takes extremely long.

At the start of the operation, a request is made to rubygems.org for dependencies of every gem, and the service throws a 422 unprocessable entity exception (output: https://dpaste.org/ghMJ). It then proceeds to download multiple spec versions of gems to make up for this failure. They have a hardcoded limit of 200 gems (https://github.com/rubygems/rubygems.org/blob/master/app/controllers/api/v1/dependencies_controller.rb#L3) and throws the error (https://github.com/rubygems/rubygems.org/blob/master/app/controllers/api/v1/dependencies_controller.rb#L25).

`time gem install aws-sdk -V`
```
real	13m38.779s
user	7m11.112s
sys	5m13.007s
```

Version 2 is much faster because there are only 3 gems to download and install.

`time gem install aws-sdk -v '~> 2' -V`
```
real	0m18.038s
user	0m7.509s
sys	0m8.031s
```

To install V3 faster, I tried using bundler and `--full-index`, and it seems to work quickly:

```
# Gemfile
source 'https://rubygems.org' do
  gem 'aws-sdk'
end
```

`time bundle install --full-index`

```
real	0m34.605s
user	0m19.129s
sys	0m5.779s
```

I will pass this to the RubyGems.org team to see if we can bump this limit.

**Comment by mullermp** [comment]
I highly recommend using service gems as needed instead of installing the `aws-sdk` gem. We would like to deprecate that gem in the future. The list of services is always growing and it always becomes a pain point.

**Comment by mullermp** [comment]
@alejomongua The change has been deployed to RubyGems.org, and it now takes about ~6 min on my machine to install aws-sdk. Thanks for reporting this.
