### ISSUE TITLE
Days is a required parameter in restore_object

### ISSUE THREAD

**Issue by CliveMillerTR** [aws/aws-sdk-ruby#2380]
In `aws-sdk-ruby/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb` `#restore_object` it should be noted that `days` is a required parameter, otherwise you get the rather unhelpful error message `The XML you provided was not well-formed or did not validate against our published schema`

**Comment by mullermp** [comment]
Thanks for reporting this. Were you restoring an object from Glacier? I have verified that `restore_object` must take `restore_request: { days: <days> }` when restoring from Glacier. The [docs](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#restore_object-instance_method) state that:

```
Objects in the GLACIER and DEEP_ARCHIVE storage classes are archived. To access an archived object, you must first initiate a restore request. This restores a temporary copy of the archived object. **In a restore request, you specify the number of days that you want the restored copy to exist.** After the specified period, Amazon S3 deletes the temporary copy but the object remains archived in the GLACIER or DEEP_ARCHIVE storage class that object was restored from.
```

Because of how this API is designed, `days` cannot be marked as required because in some instances it isn't required. When `restore_request` is empty, What is being sent to S3 is valid XML: `"<RestoreRequest xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"/>\n"`

**Comment by mullermp** [comment]
@ajredniwja could you follow up with S3 to see if they can provide a friendlier message for these cases?

**Comment by ajredniwja** [comment]
@mullermp @CliveMillerTR Going through a similar issue through JS-SDK for a different API, already in talks with the team, can discuss with the team and update here soon.

**Comment by mullermp** [comment]
Opened this on a different repo because it's for the service team. https://github.com/aws/aws-sdk/issues/28
