### ISSUE TITLE
list objects in a bucket based on 'last_modified' time

### ISSUE THREAD

**Issue by vinaymehta** [aws/aws-sdk-ruby#2437]
I want to know if there is any way we can list objects in a bucket based on last_modified time in reverse order and can apply limit on it. OR if there is any way to get latest added objects in a bucket with limit param.
Please help if we have such way using SDK
Thanks in advance

**Comment by mullermp** [comment]
Hey @vinaymehta, you can certainly do this in Ruby with something like:

```
resp = s3.list_objects_v2(bucket: my_bucket)
resp.contents.select { |o| o.last_modified > my_time }
```

As far as the API goes, I don't know if you can select on the server side, unless you use the `start_after` or `prefix` options, which would require having timestamps as your object's key.

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#list_objects_v2-instance_method

**Comment by vinay-legitimate** [comment]
Hi @mullermp, Thanks for your reply
But in above solution it will first list all objects in the bucket where I am already using `prefix` option to have files within a folder and then it will filter out those files based on last_modified time of the object.

I want if I can send `last_modified` param in the listing objects request itself. So that it should list only the required objects and not go through all objects in the bucket folder.
Thanks

**Comment by vinaymehta** [comment]
Hi @mullermp , Thanks for your reply
But in above solution it will first list all objects in the bucket where I am already using prefix option to have files within a folder and then it will filter out those files based on last_modified time of the object.

I want if I can send last_modified param in the listing objects request itself. So that it should list only the required objects and not go through all objects in the bucket folder.
Thanks

**Comment by mullermp** [comment]
If you are using `prefix`, then other than `start_after` and naming your keys with timestamps, there is no such way as far as I can tell. Perhaps open a feature request on https://github.com/aws/aws-sdk for S3 to add such a capability into the SDKs?
