### ISSUE TITLE
Ship LICENSE file with gem

### ISSUE THREAD

**Issue by priv-kweihmann** [aws/aws-sdk-ruby#2487]
https://github.com/aws/aws-sdk-ruby/blob/master/LICENSE.txt should be shipped with the gem, otherwise it's impossible to have the gem properly used with compliance tooling.
Which makes it harder to use it in a corporate environment - this gem is just picked as an example - the missing LICENSE file applies to **all** aws gems provided via rubygems.org

**Comment by mullermp** [comment]
Thanks for pointing this out. I will take a look at supporting this.

**Comment by mullermp** [comment]
Hey, thanks for opening an issue. In all of the gemspec files, there should be a [license= attribute](https://github.com/aws/aws-sdk-ruby/blob/master/build_tools/aws-sdk-code-generator/templates/gemspec.mustache#L14) that is already set to `Apache-2.0`. Does your company's corporate environment/compliance tooling look at this field? Within Amazon's internal build system for example, we have tooling that imports 3rd party Ruby gems and checks licenses on the gemspec before falling back to license files if they exist. Otherwise, because of how `files=` works in the gemspec, we would need to maintain a copy of the license file in each of our 270+ gems. This is obviously not ideal, which is why the license exists at the root today. Could you check with your company to see if they can look at the `license` attribute on the gemspec instead?

**Comment by priv-kweihmann** [comment]
@mullermp you're right about the fallback use of the license meta data field - still one can't verify the exact terms and conditions as the license text isn't available. INAL but my understanding of the Apache license is that the terms and conditions should be shipped along the source distribution (which is by nature the case with ruby).
On the other side I totally get the pain point here, shipping a non-functional big items in 200+ gems does sound like a bit of work.
I would also be fine if any kind of SPDX-like attribution would be available as part of the source files, just anything to "proof" that the meta data is correct (from my experience it isn't the case for many gems, that's why this is something I really would like to see here).
So how about adding a SPDX header to each file shipped with the gems? As a sort of compromise...

**Comment by mullermp** [comment]
You are right that the license should be shipped with the gem; I interpret "should" as if it were in an RFC, where it's recommended but not required. If I had to choose between a SPDX comment on each code generated file vs including a LICENSE.txt file with each gem, I would choose the latter because it would be less intrusive to not have to update code generation for 4000+ files. I will prepare a PR for that.

**Comment by priv-kweihmann** [comment]
@mullermp thanks
