### ISSUE TITLE
Specify signature_version v2 in Aws.config.update

### ISSUE THREAD

**Issue by stiller-leser** [aws/aws-sdk-ruby#2576]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**
I am using this gem to address an older API that requires a signature in version 2. Is there any way this can be done in newer aws-sdk versions?

**Comment by mullermp** [comment]
What API/Service are you trying to use SigV2 with? 

There is a SigV2 gem: https://rubygems.org/gems/aws-sigv2 and it's used in SimpleDB and ImportExport

**Comment by stiller-leser** [comment]
I am trying to use the EC2 API - Also, I should have mentioned that ;)

**Comment by alextwoods** [comment]
The EC2 API is modeled as sigv4, and looking back, even the [oldest version 2015-10-01](https://github.com/aws/aws-sdk-ruby/blob/version-3/apis/ec2/2015-10-01/api-2.json#L10) is sigv4.  

Is there an issue or error you're running into with sigv4?  Can you provide some example code + error messages?

In general (aside from S3), signature version isn't configurable because its specified by the service model.

**Comment by stiller-leser** [comment]
Unfortunately I was forced by the internal service to sign the requests with v2. After looking at the EC2 gem this morning, I have reimplemented the needed functionality for the service in a standalone gem. 

Thanks for all the help though!

**Comment by mullermp** [comment]
That doesn't make too much sense... but glad you were able to solve your problem.
