### ISSUE TITLE
Not able to use Multi-Region Access point with s3_client.list_objects

### ISSUE THREAD

**Issue by dmhagan77** [aws/aws-sdk-ruby#2630]
Confirm by changing [ ] to [x] below:
- [ X ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [ X ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**
How can I use s3.client list_objects to get objects from a Multi Region Access point?

 I can get it to work using the CLI without much of any effort.  But when using the aws-sdk-s3, I get something about "ArgumentError (You are attempting to sign a request with sigv4a which requires aws-crt and version 1.4.0.crt or later of the aws-sigv4 gem. Please install the gem or add it to your gemfile.)"

I have reviewed:
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#list_objects-instance_method which notes the use of...
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Types/ListObjectsV2Request.html which then references...
https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-access-points.html

And also looked here: https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html

After initializing an s3_client like I have done numerous times before, then I try to call:
```
 s3_client.list_objects({bucket: "arn:aws:s3::<account_number>:accesspoint/<multi_region_access_point_alias>.mrap"})
 ```

Gems used:
2.7.3 :012 >puts Gem.loaded_specs["aws-sdk-s3"].version
1.111.1
2.7.3 :013 > puts Gem.loaded_specs["aws-sigv4"].version
1.4.0
2.7.3 :014 > puts Gem.loaded_specs["aws-crt"].version
0.1.2

Please advise.

**Comment by alextwoods** [comment]
Thanks for opening this and sorry you're running into this issue.  To use Multi region access points, you'll need to use the crt version of the `aws-sigv4` gem. (note: CRT support for Ruby is still in developer preview, which is why it requires a special version).  I'd recommend using the [1.4.1.crt version](https://rubygems.org/gems/aws-sigv4/versions/1.4.1.crt).  If you're using a Gemfile, I'd recommend specifying the version explicitly (eg, `gem 'aws-sigv4', '1.4.1.crt'`) or if you're not using a Gemfile, install it explicitly with something like `gem install aws-sigv4 -v 1.4.1.crt`.

**Comment by dmhagan77** [comment]
Thanks for the heads up on the gems, that seems resolve my issue that I raised.  Thank you for the recommendation.
