### ISSUE TITLE
Preference for a credentialProvider when invoking Aws::CredentialProviderChain

### ISSUE THREAD

**Issue by svadnala** [aws/aws-sdk-ruby#2656]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers

**Describe the question**

We have two credentialsproviders that we use for getting temp tokens to make calls to aws services i.e InstanceProfileMetadata and WebIdentityToken

Note: The way we use WebIdentityToken is via https://github.com/aws/amazon-eks-pod-identity-webhook and Instacne

Currently we do not explicitly set/code on how to set and choose a credentialProvider and let the sdk handle this for us when making any calls to aws

Looking at the sdk code, it appears that the Default behaviour of sdk is to invoke CredentialProviderChain `Aws::CredentialProviderChain.new.resolve` https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/credential_provider_chain.rb#L11-L14 (correct me if am wrong) and based on the observation it seems that either credentials are obtained via InstanceProfileMetadata or WebIdentityToken(this one most of the times). so we see a mix of these two credentialprovider when making calls to aws services.

Question1: We're in the process of deprecating InstanceProfile way of obtaining credentials and switch to WebIdentityToken, so with the current setup, if we decommission the former, would all api calls fall back to using WebIdentityToken flawlessly for all operations to aws without disruptions. To re-iterate, there are no explicit calls or references to use either of the credentialProvider.

Questions2: is there a similar thing for ruby as the [Go_SDK](https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/credentials/chain_provider.go#L33-L47) where we can pass in arguments to a credentialprovidechain to specify the order in which credentialprovider should be choosen/used. This would help us in aiding with the deprecation as well can set the preference and test before deprecation

**Comment by mullermp** [comment]
Thanks for reaching out. You are correct about the default behavior. The credential provider chain is resolved in order and the SDK will use the first credentials that it finds.

For question 1. Instance profile credentials are last in the list. If you are seeing a mix of web identity credentials and instance profile credentials, then the conditions necessary to use web identity credentials are not being met sometimes (i.e. you may not have `AWS_RULE_ARN` or `AWS_WEB_IDENTITY_TOKEN_FILE` set in some cases). Regardless of how you got the credentials (via instance profile or web identity) there should be no disruption **assuming the credentials and associated permissions are the same**.

For question 2. No this is not supported. However, you can do a Ruby monkey patch (override the `providers` method in `Aws::CredentialProviderChain`) but this is not recommended. You could also create your own credential provider chain and "resolve it" and pass the credentials directly to your clients via the `:credentials` option.

If you're trying to move to exclusively web identity credentials, you could also initialize an instance of [AssumeRoleWebIdentityCredentials](https://github.com/aws/aws-sdk-ruby/blob/da021469505bfe3ebb3d952fbaad27436c877715/gems/aws-sdk-core/lib/aws-sdk-core/assume_role_web_identity_credentials.rb#L25) (or any credential provider of your choosing) and pass it to the `:credentials` option of the client. This is more preferred than overriding the credential chain because you are explicitly using web identity credentials each time.

**Comment by svadnala** [comment]
Thanks for clarifying on the disruption part clearly.

As mentioned earlier we're using https://github.com/aws/amazon-eks-pod-identity-webhook to have the env variables injected to the pod, so that WebIdentiyToken can be used, am not sure how would that be possible that env variables `AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE` maybe null.

since we use pod-identity-webhook, think we cannot make the use of [AssumeRoleWebIdentityCredentials](https://github.com/aws/aws-sdk-ruby/blob/da021469505bfe3ebb3d952fbaad27436c877715/gems/aws-sdk-core/lib/aws-sdk-core/assume_role_web_identity_credentials.rb#L25) as it requires passing in role_arn and token_file which are mandatory attributes and are only available via env vars

**Comment by mullermp** [comment]
Yep. As long as the credentials are the same, it shouldn't matter where they are sourced from.

You can make use of `AssumeRoleWebIdentityCredentials` by using the ENV variables as parameters, and even go as far as asserting that you have them:

```
token_file = ENV['AWS_WEB_IDENTITY_TOKEN_FILE']
role_arn = ENV['AWS_ROLE_ARN']

# raise if you don't have the things you need, maybe fetch IMDS credentials as back up? etc
raise if token_file.nil? || role_arn.nil?

credentials = Aws::AssumeRoleWebIdentityCredentials.new(web_identity_token_file: token_file, role_arn: role_arn, ...)
s3 = Aws::S3::Client.new(credentials: credentials, ...)
```

**Comment by svadnala** [comment]
Cool, thanks for the example snippet, will check with the team and get back before closing this as resolved

**Comment by mullermp** [comment]
Sounds good. I am setting this to closing soon (4 day) but you can always re-open if there's still issue.
