### ISSUE TITLE
Aws::RedshiftDataAPIService::Types::DescribeStatementResponse error is nil

### ISSUE THREAD

**Issue by mferrier** [aws/aws-sdk-ruby#2767]
### Describe the bug

When receiving a response from `Aws::RedshiftDataAPIService::Client#describe_statement` and the status of the statement is `FAILED` and there is an `error` field, the method `error` on the response returns `nil` but `response.data.error` returns the actual `error` string.

### Expected Behavior

`response.error` to return the error string, and not `nil`

### Current Behavior

`response.error` is `nil` while `response.data.error` is an error string

### Reproduction Steps

1. execute a statement that will return an error
2. execute `describe_statement` for the statement
3. once the statement is in state `FAILED`, compare `response.error` and `response.data.error`

### Possible Solution

Bad initialization?

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-redshiftdataapiservice (1.21.0)

### Environment details (Version of Ruby, OS environment)

occurs on both `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm64-darwin21]` and on AWS lambda ruby 2.7

**Comment by mullermp** [comment]
This is expected behavior. `response.error` will usually contain networking errors or modeled API/HTTP errors like 404 etc. Redshift's API for this operation seems to be modeled/design to return you a successful 200 response most of the time, with a possible error on the describe statement, as a modeled member (`response.data.error`).

What's weird is the delegation that exists in the Ruby SDK, where `response.<member>` will forward to `response.data.<member>`, and in this case, there exists a shape in the API `error` that is a String, that supersedes `response.error` which is either nil or a Ruby error type, usually a networking error or a server side provided error.

In a new major version of the Ruby SDK, we would remove this delegation, which would cause this confusion and sometimes breakage.

**Comment by mferrier** [comment]
@mullermp thanks for the response. So when working with the actual result of the query, we should be looking at `reponse.data`, e.g. `response.data.status` and not `response.status`?

**Comment by mullermp** [comment]
In theory yes, however, the current SDK "feature" allows for delegating to `data` from the response (https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/seahorse/client/response.rb#L7). I think in rare cases, like shapes named "error" (this case), "context", or shapes named after enumerable methods like "count", you must use `response.data.<member>`. It's up to you if you want to use it all the time or only in this specific case.
