### ISSUE TITLE
Change in return type of state method of Aws::EC2::Instance

### ISSUE THREAD

**Issue by sangamcse** [aws/aws-sdk-ruby#2812]
### Describe the bug

There has been a sudden change in `Aws::EC2::Instance.new('instance_id').state`. Doc, as well as the previous response to the API call, was the `Aws::EC2::Types::InstanceState` format and suddenly it is giving a `Hash` response.

### Expected Behavior

```ruby
[1] pry(main)> i = Aws::EC2::Instance.new('instance_id')
[2] pry(main)> i.state
=> #<struct Aws::EC2::Types::InstanceState code=16, name="running">
```

### Current Behavior

```ruby
[1] pry(main)> i = Aws::EC2::Instance.new('instance_id')
[2] pry(main)> i.state
=> {:code=>16, :name=>"running"}
```

### Reproduction Steps

```ruby
[1] pry(main)> i = Aws::EC2::Instance.new('instance_id')
[2] pry(main)> i.state
```

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

`gem 'aws-sdk-resources', '2.11.363'`

### Environment details (Version of Ruby, OS environment)

ruby 2.6.3p62
Rails 6.0.5
macOS 13.0.1

**Comment by mullermp** [comment]
aws-sdk-resources 2.11.363 is from 2019. Are you saying you updated to that version recently and saw the change in type? Or the type changed in the same version?

**Comment by sangamcse** [comment]
We have not done any updation recently and using this version since 2019. We saw change on response without doing any version change

**Comment by mullermp** [comment]
That's odd. Did your Jmespath gem version change by chance?

**Comment by sangamcse** [comment]
Yes, that was changed to 1.6.1 from 1.4.0 recently

**Comment by mullermp** [comment]
I can confirm with the latest V3 version and JMESPath that this is not an issue.
```
[7] pry(Aws)> JMESPath::VERSION
=> "1.6.2"
[8] pry(Aws)> Aws::EC2::Instance.new('i-123').state
[Aws::EC2::Client 200 0.455222 0 retries] describe_instances(instance_ids:["i-123"])  
=> #<struct Aws::EC2::Types::InstanceState code=80, name="stopped">
```
The issue was introduced in jmespath 1.5.0 only for Ruby SDK V2 - related comment: https://github.com/jmespath/jmespath.rb/pull/51#issuecomment-1204384176. We had previously confirmed that V3 and jmespath are backwards compatible after the change.

V2 is deprecated even before we made this change to jmespath. We do not release new versions of v2. 

I think you should pin your jmespath version to 1.4.0, or upgrade to V3 of the SDK. V2 to V3 upgrade is mostly backwards compatible and can in most cases be done by changing dependencies and a few config options.

**Comment by sangamcse** [comment]
Thank you for the detailed explanation.
