### ISSUE TITLE
Chime: event_ingestion_url will be nil when use_fips_endpoint is true

### ISSUE THREAD

**Issue by codebender** [aws/aws-sdk-ruby#2881]
### Describe the issue

I was surprised that `event_ingestion_url` was returned as `nil` when calling `create_meeting` or `create_meeting_with_attendees`.  The documentation says this will be a String. `use_fips_endpoint` being set to `true` seems to be the logical reason why.  I think maybe it would be nice to document that. What do you think?

### Links

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Chime/Types/MediaPlacement.html
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Chime/Client.html#create_meeting-instance_method
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Chime/Client.html#create_meeting_with_attendees-instance_method

**Comment by yenfryherrerafeliz** [comment]
Hi @codebender, thanks for creating this issue. I have contacted the service team to get more clarity on this. As soon as they reply me back I will provide you with an update.

Ticket: V957091652

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @codebender, I have gotten confirmation from the service team that this behavior is expected, since Event Ingestion service is not in scope of FedRamp, and that is why meetings created via fips endpoints do not have url for event ingestion. I know it would be great if the documentation makes this clearer, and I have relay this sentiment to the right team so they can take further action.

Again thanks for bringing this into our attention. I will close this issue but if you need anything else that we can help you with feel free in opening a new issue.

Thanks!

**Comment by codebender** [comment]
> Hi @codebender, I have gotten confirmation from the service team that this behavior is expected, since Event Ingestion service is not in scope of FedRamp, and that is why meetings created via fips endpoints do not have url for event ingestion. I know it would be great if the documentation makes this clearer, and I have relay this sentiment to the right team so they can take further action.
> 
> Again thanks for bringing this into our attention. I will close this issue but if you need anything else that we can help you with feel free in opening a new issue.
> 
> Thanks!

I thought that this issue was the path to getting the documentation updated.  I understand this is the expected behavior now and why, so having the documentation corrected would be great!
