### ISSUE TITLE
aws-sigv4/eventstream released a minor version bump after removing support for Ruby 2.3/2.4

### ISSUE THREAD

**Issue by kumar1202** [aws/aws-sdk-ruby#2956]
### Describe the bug

The **aws-sigv4** gem used by Vault gem started failing when the aws-eventstream and aws-sigv4 gems were upgraded to [1.3.0](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-eventstream/CHANGELOG.md#130-2023-11-22) and [1.7.0](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sigv4/CHANGELOG.md#170-2023-11-22) respectively.

I understand that Ruby 2.3 is EOL but the release should have been a major version bump. As this will start failing gems which have pessimistically locked the above gem as dependencies constrained on `~> 1`. 

### Expected Behavior

The release should have been a major version bump, instead it's minor version bump and still breaks backward compatibility.

### Current Behavior

Installing aws-sigv4 breaks on 2.3.1

### Reproduction Steps

`gem install aws-sigv4` 

expects Ruby version >=2.5

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sigv4, aws-eventstream

### Environment details (Version of Ruby, OS environment)

Ruby 2.3.1, Ubuntu 20.04

**Comment by mullermp** [comment]
Thanks for opening an issue. I'm sorry for this. This was intended, warned (via blog post and rubyweekly), and we've dropped runtime versions within minor versions in the past. Please use bundler and a Gemfile instead of relying on gem install. bundler >= 1.13 will automatically compare runtime versions against the gemspec. Please also refer to our [maintenance policy](https://docs.aws.amazon.com/sdkref/latest/guide/maint-policy.html).

**Comment by rlindgren** [comment]
@mullermp this means that we are no longer able to install previous versions of gems that depend on these gems. it is no longer possible to install `aws-sdk-s3` at version `1.138.0` in an environment where only ruby 2.3 is available. this should be possible as specified here: https://rubygems.org/gems/aws-sdk-s3/versions/1.138.0

is this expected?

**Comment by mullermp** [comment]
You should be able to install s3 version 1.138.0 with ruby 2.3. You may also need to specify the dependency versions such as core version 3.187.1. For gems that depend on the AWS gems, you'll need to install these versions first. I would recommend instead to use bundler and declare a Gemfile that depends on your gem (or s3), so that dependencies are automatically resolved.

**Comment by rlindgren** [comment]
thank you @mullermp
