### ISSUE TITLE
aws-sdk-s3 version 1.165.0 invalid configuration option

### ISSUE THREAD

**Issue by kddnewton** [aws/aws-sdk-ruby#3113]
### Describe the bug

Stubbing s3 and then initializing a cloudformation client fails.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

I expect this to succeed the same as previous versions.

### Current Behavior

It gives an argument error.

### Reproduction Steps

Here is a test that fails on the latest s3 client:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "aws-sdk-cloudformation"
  # gem "aws-sdk-s3", "1.164.0"
  gem "aws-sdk-s3", "1.165.0"
  gem "base64"
  gem "minitest", require: "minitest/autorun"
  gem "nokogiri"
end

class Test < Minitest::Test
  def test_behavior
    Aws.config[:s3] = {
      stub_responses: {
        get_object: true,
        put_object: true
      }
    }

    Aws::CloudFormation::Client.new(
      region: "us-east-1",
      credentials: Aws::Credentials.new("foo", "bar")
    )
  end
end
```

If you switch the comments to use 1.164.0, it will work.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 and aws-sdk-cloudformation

### Environment details (Version of Ruby, OS environment)

3.4.0-dev, macOS

**Comment by alextwoods** [comment]
Thanks for reporting this and for the great reproduction.  It looks like the issue is caused by the recent autoload PR (#3105) which  adds autoload for service clients.  Service client's on require add their service identifier to the global config plugin's list of identifiers which it uses to filter out config ([example from s3](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L60): `Aws::Plugins::GlobalConfiguration.add_identifier(:s3)`).

I'll get a fix out today, but in the mean time, you can get around this by using S3 Client (eg just a `Aws::S3.const_get(:Client)`) before creating the cloudwatch client:

```ruby
Aws.config[:s3] = {
  stub_responses: {
    get_object: true,
    put_object: true
  }
}

Aws::S3.const_get(:Client) # this triggers the autoload and ensures s3's service id is added to the global config plugin.

Aws::CloudFormation::Client.new(
  region: "us-east-1",
  credentials: Aws::Credentials.new("foo", "bar")
)

```

**Comment by kddnewton** [comment]
Perfect, thanks @alextwoods!

**Comment by kddnewton** [comment]
(Confirmed, that does indeed fix my problem.)

**Comment by alextwoods** [comment]
We've released the [fix](https://github.com/aws/aws-sdk-ruby/commit/2c4fe8bebf11befc26af9dfaa52545280a18f95a) - [aws-sdk-s3@1.166.0](https://rubygems.org/gems/aws-sdk-s3/versions/1.166.0) and later should no longer have this issue.
