### ISSUE TITLE
Update Aws::Sigv4::Signer to use credentials hierarchy

### ISSUE THREAD

**Issue by HarlemSquirrel** [aws/aws-sdk-ruby#3147]
### Describe the feature

Many clients like `Aws::S3::Client` can be used without specifying credentials or credential provider and have a hierarchy in which they attempt to load credentials. This is useful for allowing the same code to work seamlessly in different environments such as locally with granted or deployed in ECS.

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#initialize-instance_method

The `Aws::Sigv4::Signer` class does not have this and therefore needs credentials specified. 

This workaround showcases that the credentials from other clients can work just fine:

```rb
signer = Aws::Sigv4::Signer.new(
  service: "execute-api",
  region: "us-east-1",
  # Borrow the credentials from another client that loads them for us with hierarchy
  credentials_provider: Aws::S3::Client.new.config.credentials
)
```

### Use Case

I would like to be able to be able to do this

```rb
signer = Aws::Sigv4::Signer.new(
  service: "execute-api",
  region: "us-east-1"
)
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

aws-sigv4 (1.10.1)

### Environment details (OS name and version, etc.)

N/A

**Comment by mullermp** [comment]
Thanks for opening a feature request. The Sigv4 gem is intended to be for generic signing, which requires properties like region, service, and the credentials. We could consider searching the credential provider chain for credentials on sigv4 however it would be costly, because it would search, env, files, and sometimes make network calls. 

For ECS, have you looked at just passing an instance of [ECSCredentials](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECSCredentials.html) to the credentials provider instead of borrowing resolved client credentials? You can also invoke API private `Aws::CredentialsProviderChain.new`.

**Comment by HarlemSquirrel** [comment]
> Thanks for opening a feature request. The Sigv4 gem is intended to be for generic signing, which requires properties like region, service, and the credentials. We could consider searching the credential provider chain for credentials on sigv4 however it would be costly, because it would search, env, files, and sometimes make network calls.
> 
> For ECS, have you looked at just passing an instance of [ECSCredentials](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/ECSCredentials.html) to the credentials provider instead of borrowing resolved client credentials? You can also invoke API private `Aws::CredentialsProviderChain.new`.

Yeah I added a check so if one of the ECS ENV variables is set we use `ECSCredentials` so it's faster in production. Otherwise, use the chain.

**Comment by mullermp** [comment]
That should work. I realize that we can't put the chain in this gem anyway because it would need to depend on core, which depends on sigv4, which is a circular dependency. I think aside from that, we want to have the sigv4 gem continue to be generic and not have knowledge of where and how credentials are loaded. I do understand that you want them to be loaded more easily. We have gotten a few requests over the years about making the chain public. It is technically a private API. I will think more on this.
