### ISSUE TITLE
Waiter for secondary indexes

### ISSUE THREAD

**Issue by thomaswitt** [aws/aws-sdk-ruby#3149]
### Describe the feature

When creating secondary indexes, DynamoDB can take a significant random time, even on an empty database. On one hash_key only index (no range key) I am waiting for about 2-3 minutes until it exits the backfilling state.

When you want to create data in a migration which depends on the new index, this is bad.

For creating a table, there's a handy [Waiter](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/DynamoDB/Waiters.html) in the Gem, but that only works on table_exists and table_not_exists.

When using the AWS CLI, I can get the index status:
```
. $ aws dynamodb describe-table --table-name MYAPP_production|jq '.Table.GlobalSecondaryIndexes[] | {IndexName, IndexStatus}'
{
  "IndexName": "user_email_gsi",
  "IndexStatus": "ACTIVE"
}
```

It would be great if that waiter would be available natively in the SDK. 

### Use Case

Creating data which depends on the existance of a new secondary index.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

latest

### Environment details (OS name and version, etc.)

latest

**Comment by mullermp** [comment]
Thanks for the feature request. This unfortunately is an upstream request to the dynamodb team who owns the modeling which includes waiters. I can't guarantee delivery or timeline of these.

**Comment by RanVaknin** [comment]
Hi @thomaswitt ,

I have upstreamed your request to the DDB service team (PFR ID `#a2vRU000000GW7BYAW`), however we don't have visibility to when / if this is going to be implemented.

For the sake of transparency, I noticed that the Dynamodb service [barely models waiters](https://github.com/aws/aws-sdk-ruby/blob/version-3/apis/dynamodb/2012-08-10/waiters-2.json) at all and the last one was added about 8 years ago. If this will get implemented it will likely be done as a broader effort to add all missing waiters.

Since this issue is not actionable by the AWS SDK team, I'm inclined to close this. If you wish, and if you have access to AWS support via the developer console, you can cut a ticket to AWS support to check the status of this feature request using the PFR ID provided above.

Thanks again,
Ran~
