### ISSUE TITLE
Net::HTTP content-length Error When Yielding to Block

### ISSUE THREAD

**Issue by lanrion** [aws/aws-sdk-ruby#557]
#<AWS::Core::Http::NetHttpHandler
::TruncatedBodyError: content-length does not match> /home/service/.rbenv/versio
ns/1.9.3-p448/lib/ruby/gems/1.9.1/gems/aws-sdk-1.32.0/lib/aws/core/http/net_http
_handler.rb:83:in `ensure in block (2 levels) in handle'

**Comment by trevorrowe** [comment]
Going back to this issue. Based on the discussion, I'm going to close this old issue. The SDK is working as indented by raising an error when fewer than expected bytes have been received from the remote end. I realize the source of the unreliable connection may still be unknown, but there have been no reports or comments on this issue. Also, v2 has been stable for quite a while now.

If there is further actionable information, then we can re-open the issue.

**Comment by bjeanes** [comment]
FWIW, I see this issue only when writing to file in block

I'm on an old version still (1.40.3), so I know this is well into "not supported" territory, but I don't see this mentioned above explicitly.

Compare writing to a `StringIO` vs a `Tempfile` (100% reproducible in each branch, for me):

``` ruby
> f = Tempfile.new(['x', '.ris'])
=> #<Tempfile:/var/folders/z1/60kf0jdj67s66tsc1ygv7vcm0000gn/T/x20170718-16614-wmx94k.ris>
> obj.read { |chunk| f.write(chunk) }
AWS::Core::Http::NetHttpHandler::TruncatedBodyError: content-length does not match
	from /Users/bjeanes/.gem/ruby/2.2.6/gems/aws-sdk-1.40.3/lib/aws/core/http/net_http_handler.rb:83:in `ensure in block (2 levels) in handle'
	from /Users/bjeanes/.gem/ruby/2.2.6/gems/aws-sdk-1.40.3/lib/aws/core/http/net_http_handler.rb:83:in `block (2 levels) in handle'
	[... snip ...]
> s = StringIO.new
=> #<StringIO:0x007fef412e0288>
> obj.read { |chunk| s.write(chunk) }
[AWS S3 200 12.151541 0 retries] get_object(:bucket_name=>"[redacted]",:key=>"[redacted]")
=> {:meta=>{}, :restore_in_progress=>false, :content_type=>"", :etag=>"\"2ba34e5ec00d3c718b104987f18c5069\"", :accept_ranges=>"bytes", :last_modified=>2017-07-18 05:08:05 +0000, :content_length=>28541588, :data=>nil}
```

Obviously, reading into a `StringIO` completely side-steps the advantage of chunked fetching, so this is merely illustrative.

Again, this is on an older version but I thought this may still be helpful if the issue is continuing in some fashion.

**Comment by bjeanes** [comment]
Some further info. The exception only happens if I write the `chunk` to the file. If I write something else, the exception does not occur:

``` ruby
> obj.read { |chunk| f.write("0") }
[AWS S3 200 10.965613 0 retries] get_object(:bucket_name=>"[redacted]",:key=>"[redacted]")
=> {:meta=>{}, :restore_in_progress=>false, :content_type=>"", :etag=>"\"2ba34e5ec00d3c718b104987f18c5069\"", :accept_ranges=>"bytes", :last_modified=>2017-07-18 05:08:05 +0000, :content_length=>28541588, :data=>nil}
> f.rewind
=> 0
> f.read(100)
=> "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
```

I added a counter to see how many chunks it processes:

``` ruby
> n = 0
=> 0
> f.truncate(0)
=> 0
> obj.read { |c| n += 1; f.write(c) }
AWS::Core::Http::NetHttpHandler::TruncatedBodyError: content-length does not match
	[... snip ...]
> f.rewind
=> 0
> f.size
=> 34212
> n
=> 8
```

In a completely un-scientific test of a "handful" of times, it always failed on the 8th chunk and always only wrote 34112 bytes, at least with my specific test file.

I suspected the presence of a `raise` in `ensure` block of `AWS::Core::Http::NetHttpHandler` is masking the original exception. Indeed, after modifying my local copy of the gem to preserve log this exception, I discovered that the origin is an encoding exception (at least in my case): `#<Encoding::UndefinedConversionError: "\xCB" from ASCII-8BIT to UTF-8>`

A cursory glance at the implementation in the latest version (well, master) implies that this issue is no longer present due to no longer using performing the length check in the context of an `ensure` clause.

So, this probably is actually fixed. However, for people in older versions of the gem, perhaps ensure your file is open in binary mode first. This worked for me:

```
> f.truncate(0); obj.read { |c| f.write(c) }
AWS::Core::Http::NetHttpHandler::TruncatedBodyError: content-length does not match
> f.binmode
=> #<File:/var/folders/z1/60kf0jdj67s66tsc1ygv7vcm0000gn/T/x20170718-18872-1ewghxw.ris>
> f.truncate(0); obj.read { |c| f.write(c) }
[AWS S3 200 10.536865 0 retries] get_object(:bucket_name=>"[redacted]",:key=>"[redacted]")
=> {:meta=>{}, :restore_in_progress=>false, :content_type=>"", :etag=>"\"2ba34e5ec00d3c718b104987f18c5069\"", :accept_ranges=>"bytes", :last_modified=>2017-07-18 05:08:05 +0000, :content_length=>28541588, :data=>nil}
> f.size
=> 28541588
```

**Comment by awood45** [comment]
Thanks for the extra notes here.
