### ISSUE TITLE
occasional AWS::Errors::MissingCredentialsError

### ISSUE THREAD

**Issue by smojtabai** [aws/aws-sdk-ruby#587]
We are using aws-sdk-ruby on ec2 (specifically writing to s3) in a script, it is running on about 100-200 hosts. This script is running multiple times every 5 minutes on those hosts and we are occasionally getting AWS::Errors::MissingCredentialsError. We rely on the EC2 credential provider. We initially thought that sometimes the failure was happening because the call to get the info was failing so we put a retry block with something like s3client.config.credential_provider.refresh but we are still getting the error. Any ideas?

**Comment by mikeys** [comment]
To whoever it may concern:
I think that the issue may be a bit different than what has been described and is a result of wrong thread handling:

In `https://github.com/aws/aws-sdk-ruby/blob/aws-sdk-v1/lib/aws/core/credential_providers.rb#L48`:
```ruby
        def set?
          @cache_mutex ||= Mutex.new
          unless @cached_credentials
            @cache_mutex.synchronize do
              @cached_credentials ||= get_credentials
            end
          end
          !!(@cached_credentials[:access_key_id] &&
            @cached_credentials[:secret_access_key])
        end
```

Using `EC2Provider` - Every thread which tries to fetch `credentials`, basically resets `@cached_credentials` if `near_expiration?` is true:
```ruby
        # Clears out cached/memoized credentials.  Causes the provider
        # to refetch credentials from the source.
        # @return [nil]
        def refresh
          @cached_credentials = nil
        end
```

That means that moderate amount of threads which call the `credentials` method concurrently near the credentials expiration time, will cause `get_credentials` to get evaluated a lot of times (since each one `clears` the cache of the current thread in the "synchronize" block) even though it's "one-at-a-time" which will cause bombarding of the meta-data endpoint, and I assume this is why the response takes more than a second.
