### ISSUE TITLE
Polling with a dead letter queue

### ISSUE THREAD

**Issue by agoodno** [aws/aws-sdk-ruby#629]
I've setup a dead letter queue with my main queue. What I expected was that if I re-raise an exception in the body of the poll() method (see below) that the message would not be marked as deleted and when the number or receive count (configured) is reached, that the message would be moved to the dead letter queue. Instead what happens is that any exception raised does move the message to the dead letter but also exits the polling process. Is this intended? It seems to me like receive_message() method in the source correctly raises the exception but that poll (which calls receive_message) should not allow it to propagate all the way out and should continue looping.

If I comment out the re-raise below, the polling process doesn't exit but the message is marked deleted so never makes it to the dead letter queue.

    begin
      log.info "Polling queue #{q.url}"
      q.poll do |msg|
        log.info "Retrieved the message '#{msg.body}'"
        begin
          ..do work here which might raise an exception..
        rescue Exception => e
          log.error "#{e.message}, will skip processing of this message"
          raise e
        end
      end
    rescue Interrupt
      log.info "Processor shutdown due to user interrupt"
    end

**Comment by trevorrowe** [comment]
The `#poll` method as implemented automatically deletes messages if the block returns normally. If you trap the error inside the block, then the message will be deleted. 

This is intentionally, as we don't want the SDK to swallow unexpected errors. What is lacking here is a way for your to indicate that the message should not be deleted because you encountered an error that made it not possible to process. 

Would something like this work:

```ruby
q.poll do |msg|
  throw :failed # exit the block without deleting the message or raising
end
```

**Comment by trevorrowe** [comment]
I'm going to close this issue for now. There are no plans to change this behavior in the v1 sdk, as it would be a breaking change. I do plan to address this as part of v2 when a polling abstraction is added to the Queue class.
