### ISSUE TITLE
Allow AWS.config setting for retries in the EC2 credential provider

### ISSUE THREAD

**Issue by rb2k** [aws/aws-sdk-ruby#717]
As mentioned over here: https://github.com/aws/aws-sdk-ruby/pull/634#issuecomment-76028716
It would be nice to have a way to set this as part of the global configuration.

**Comment by wjordan** [comment]
For reference, the AWS CLI (via `botocore`) allows configuration of EC2 credential retries/timeouts through `metadata_service_num_attempts` / `metadata_service_timeout` variables in the global configuration as well as `AWS_METADATA_SERVICE_TIMEOUT` / `AWS_METADATA_SERVICE_NUM_ATTEMPTS` environment variables (see [source](https://github.com/boto/botocore/blob/934b229c116b22dd143a4ef0f5c4fe7e31e62699/botocore/session.py#L98-L107)).

If this feature is ever implemented in the Ruby SDK it would be nice to re-use these existing names for reuse/consistency across the two SDKs.

**Comment by wjordan** [comment]
@mullermp could you please reopen this issue, now that the Feature Requests backlog markdown file has been deprecated/removed?

**Comment by mullermp** [comment]
I'd have to check in with other SDKs on whether to support this or not. Generally, customers request features to other SDKs because "CLI does it" but sometimes it's not necessary because of the nature of CLI versus a language SDK.

**Comment by mullermp** [comment]
It looks like this original feature request was already implemented (for allowing retries through code) so I'm going to close this.

For supporting global configuration and environment variables, we should open a new feature request and then I would need to check with other SDK teams on whether they can support it. Generally CLI has different configuration mechanisms because .. it's the CLI (and files/ENV makes sense) over code configuration (language runtime).
