### ISSUE TITLE
Aws::S3::Client.new requires AWS_REGION env var to be set

### ISSUE THREAD

**Issue by chr0n1x** [aws/aws-sdk-ruby#729]
Trying to run some code on my AWS instance with an IAM role. I'm trying to do:
`Aws::S3::Client.new.list_buckets`

I already have `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` set in my runtime environment, both set through IMDS. What I get:

```
/.../gems/aws-sdk-core-2.0.29/lib/aws-sdk-core/plugins/regional_endpoint.rb:30:in 'after_initialize': missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
```

Setting `AWS_REGION` to what `placement/availability-zone` gives me from IMDS, I see that the `Client` object is trying to query `s3.us-east-1a.amazonaws.com:443`. What ends up happening:

`/.../ruby/net/http.rb:883:in 'initialize': getaddrinfo: Name or service not known (Seahorse::Client::NetworkingError)`

Any idea as to what I could be doing wrong?

**Comment by trevorrowe** [comment]
The placement availability zone is a little bit different than the region. Each Amazon EC2 region has multiple azs, named with different letter suffixes, e.g. us-east-1a, us-east-1b, etc. The actual region name is "us-east-1".

The SDK does not attempt to validate the region name because:

* New regions are brought online frequently and we don't want to force SDK updates to access them.
* It can be helpful for testing purposes to fake a region

As a result, the SDK is following this pattern to build the endpoint:

```ruby
"ec2.#{region}.amazonaws.com"
```

If you prune the letter from the end of the region name, you should get what you are looking for. Please re-open if this doesn't resolve your issue.

**Comment by trevorrowe** [comment]
Also, if you didn't know, the SDK will automatically load the instance profile credentials from the IMDS without extra configuration. You should not need to export credentials to ENV. The benefit of letting the SDK grab these on your behalf is that it will automatically refresh credentials from the IMDS before they expire.

**Comment by chr0n1x** [comment]
@trevorrowe yeah, I tried removing all of my code that pulled credentials from IMDS out. Still had to set a region, but that worked. It's kind of sad that I have prune it though.

Thanks for the help!

**Comment by trevorrowe** [comment]
The region is still required because there is no requirement that you must access AWS endpoints from the region your EC2 instance is running. The SDK will not ever provide a default region. If, by convention, you always access S3, IAM, or whatever service, in the same region as your instance, then pulling the AZ from IMDS is an option, but you do have to remove the suffix.
