### ISSUE TITLE
Allow custom waiters

### ISSUE THREAD

**Issue by danielsiwiec** [aws/aws-sdk-ruby#738]
It would be nice to have an option to wait for an arbitrary attribute value, rather than be limited to a fixed list of waiters. For instance:

```ruby
operation = Proc.new { |instance| instance.public_dns_name.nil? }
instance.wait_until(&operation)
```

**Comment by trevorrowe** [comment]
The implementation for this method would be fairly straightforward.  Internally it would yield a loaded object, refreshing self until the block returned a true value. The biggest question is how to ensure it has a consistent interface for max attempts, delay, etc to prevent polling indefinitely.

**Comment by danielsiwiec** [comment]
Hmm, that's a very good question. For my need I hand-rolled the mechanism, but it feels like I'm duplicating logic, that's already there:

```ruby
class Waiter
  def initialize(options)
    @options = options
  end

  def wait
    attempts = 0
    while @options[:poller].call && attempts < @options[:max_attempts]
      sleep(@options[:delay])
      attempts += 1
    end
  end
end

operation = Proc.new {
  instance = ec2.instance(instance.instance_id)
  instance.public_dns_name.empty?
}

waiter = Waiter.new(
  poller: operation,
  max_attempts: 20,
  delay: 1,
)

waiter.wait
```

My naive thinking makes me hope that if we opened up the Waiter and Poller classes and let people create them with a custom ```operation``` and pass it in, it would *magically* work.
Someone with a deeper understanding of the ```Poller``` would have to testify to that though.

**Comment by danielsiwiec** [comment]
Trevor, I took a stab at implementing a custom waiter. I also tried to follow your testing convention. Please look at the commit above and let me know what you think.

Pros:
- reused the original waiting logic
- the interface is very easy to use ```instance.wait_until(&condition)```

Caveats:
- implemented only in EC2::Instance class (I'd need some guidance with how to implement the function across all resources, if needed)
- hardcoded waiter parameters

Let me know what you think about the approach. I haven't written any docs yet, but if this gets a green light, I'll definitely add some.

**Comment by trevorrowe** [comment]
I like the general approach. I took your idea and refined it a bit. I was interested in a generic solution that would work for all resource types. I pushed a proof-of-concept branch. It lacks automated tests, but it passes all of the smoke tests I ran it through manually.

https://github.com/aws/aws-sdk-ruby/commit/f9e33b4c8b0a3e26e95c61bb84ae046bd9f47355

Some thoughts:

* Its difficult to know what a sensible max attempts and delay values to use. Some resources would do better with shorter polling loops, where others would want longer ones. They can be provided as options, which is okay.
* I opted to have the waiter return the resource object so it can be chained, instead of the response from the load operation: `resource.wait_until(&condition).do_something`\
* I am using the resource `#reload` method to force updates on the resource data. Unfortunately, not every resource can be loaded. This is not common, but the code would need to raise some sort of `NotImplementedError` when attempting to call `#wait_until` on a resource that can not be refreshed.

Thoughts?

**Comment by danielsiwiec** [comment]
I like what you did with the idea. I'm curious why you're counting the attempts in the Poller. Isn't Waiter already doing this?

I agree with max attempts and delay dilemma. As the custom waiter is more *open* than wait_until_something, I feel like we're passing more power to the user and one could say that with this power comes a great responsibility to set the values :)

I also like the resource being the returned value. I wonder why the ```Client.wait_until``` isn't doing this too. I struggled to make a good use of ```PageableResponse```

On a different note - I don't see ```reload``` being documented anywhere and it is really useful!

Anything I can do to help? Add some tests maybe?

**Comment by trevorrowe** [comment]
I use the attempts counter to prevent the poller from reloading the resource when no more polling attempts will be made. Its more of an optimization. I could have achieved the same result be register a `:before_wait` callback and then reload from there. I did not do that because I don't want to interfere with the user's optional `:before_wait` callback.

The `Client#wait_until` returns the response because it has no concept of a resource. It polls an operation for a successful or failure state, returning the response that indicates success. Resource waiter methods have the extra context and return an instance object.

This brings up an interesting question. Calling `Instance#wait_until_running` will not internally reload the instance. Instead it uses the `Client#wait_until(:instance_running)` method to poll and then constructs and returns a new `Instance` object. If the response from `Client#wait_until` happens to return the appropriate data, it will populate the data on the returned instance. This makes it possible to chain calls like:

```ruby
instance.wait_until_running.state.name
#=> 'running'
```

However it also means the following is possible:

```ruby
stopped_instance.state.name
#=> 'stopped'

stopped_instance.start
running_instance = stopped_instance.wait_until_running

stopped_instance.state.name #=> 'stopped'
running_instance.state.name #=> 'running'
```

The intention was to never update data of a resource unless the user explicitly calls `#reload`. Does calling a waiter method express that direct intent and should therefore both forms of waiters update the internal data, or should be waiter forms chain a new copy of the resource with updated data. One is thread-safe, the other isn't.

**Comment by trevorrowe** [comment]
Also, the `#reload` method is documented in the parent class for all resources:

http://docs.aws.amazon.com/sdkforruby/api/Aws/Resources/Resource.html#load-instance_method

I understand this is not the most obvious thing. I'm considering explicitly calling it out on each resource class.

**Comment by danielsiwiec** [comment]
Now I see what you mean with the optimization. The way I was doing it, I was reloading the resource **before** calling the block. That way I didn't have to check the max attempts, but I was doing a possibly redundant API call at first iteration, if the instance is already in the desired state. Performance vs code readability...

The problem of updating the internal state of the resource is indeed interesting. On one hand, implicit state changes are a debugging nightmare and, like you mentioned, not thread safe. Also, a *wait* method name doesn't suggest state change (maybe add ```wait_until!``` would?) and could be confusing.
On the other hand, a resource is usually a representation of a remote object and it's desired for the state to be current.

I think whichever approach is fine, given it's consistent with the behavior of other methods. Currently, my impression is the resource instance is really a *snapshot* of the remote object in a given point in time, unless explicitly reloaded. In that case, this situation is acceptable and understood:

```ruby
stopped_instance.state.name #=> 'stopped'
running_instance.state.name #=> 'running'
```

Does it make sense?

**Comment by trevorrowe** [comment]
Yes, it makes sense. Currently, I'm inclined to modify the sample to create a copy of the resource and load that instead of mutating the current instance. This would be consistent with the other `#wait_until_n` methods and it avoids thread safety issues.  Explaining when a resource changes state is now a very clear, "only when you call `#reload`".

**Comment by danielsiwiec** [comment]
Cool! Let me know if you'd like to see a pull request for this. I'd like to contribute to this.

**Comment by trevorrowe** [comment]
Sure. It lacks a few of the discussed code changes, documentation with examples, and the test. If you'd like to submit these that would be great.

**Comment by danielsiwiec** [comment]
Working on it. How do you feel about the interface of the method? 

In the implementation you suggested, the block is the actual waiting operation. A usage could look like this:

```ruby
resource.wait_until(max_attempts:10) {|instance| instance.state == 'running'}
```

While I really like the brevity of this approach, it's not very consistent with other waiter methods, like:

```ruby
Client.wait_until(:instance_running) {|waiter| waiter.max_attempts=10}
```

The implementation could be modified, to accept a Proc as an argument and yield the waiter to the block, like this:

```ruby
resource.wait_until(Proc.new {|instance| instance.state == 'running'}) {|waiter| waiter.max_attempts=10}
```

 Thoughts?

**Comment by danielsiwiec** [comment]
I modified the implementation, added some specs and did a brief smoke test. All looks good. Still need to add documentation.
@trevorrowe - for some reason I had the hardest time ever creating a copy of the resource and eventually came up with this:

```ruby
resource_copy = self.class.new(@identifiers.merge(client:@client, data:@data))
```

Let me know about the interface dilemma above and I'll start with the docs.

**Comment by trevorrowe** [comment]
To answer your question about the interface. If I had a do-over, the other waiter methods would not yield the water to the block, there simply wouldn't be a block argument. Short of deprecating `Client#wait_until` in favor of a similarly named method, that cannot/will not change.

I glanced through the code changes and they look good. Your copy method works. Does a vanilla dup not also work? I haven't checked this out locally yet, so I'll try to give a more complete review tomorrow.

**Comment by danielsiwiec** [comment]
#dup **does** work. Ruby is not really my first language...
Working on the docs now and will be ready soon

**Comment by danielsiwiec** [comment]
@trevorrowe Pull request ready!

**Comment by trevorrowe** [comment]
Awesome. I'm going to close this issue, in favor of #744.  I'll hopefully review this tomorrow when I am in the office. Thanks!

**Comment by danielsiwiec** [comment]
@trevorrowe Hi Trevor, I see this still hasn't been merged in from the custom-waiter branch. Is it just oversight or has it been de-prioritized?

**Comment by trevorrowe** [comment]
This is an oversight. I thought I had merged it into master already, but it appears I had only merged from your branch into custom-waiters. I'll take care of that now.

**Comment by trevorrowe** [comment]
It has been merged!

**Comment by danielsiwiec** [comment]
Thanks!
