### ISSUE TITLE
EMR - missing create_cluster / terminate_cluster

### ISSUE THREAD

**Issue by shaicoleman** [aws/aws-sdk-ruby#739]
Some functionality is missing compared to the AWS CLI for EMR, e.g. create_cluster and terminate_cluster

**Comment by trevorrowe** [comment]
The CLI has a set of customized commands the bind multiple API calls to implement these. There is no "CreateCluster" and "TerminateCluster" API operation. In order to support these methods, we would need to crack open the CLI and see what it is doing. I'm not opposed to this, but it is not as trivial as adding support for an existing API call.

**Comment by shaicoleman** [comment]
In that case it might make more sense to first create APIs for these methods, and build a wrapper around that when that becomes available

**Comment by eniskonuk** [comment]
@trevorrowe: We had the same problem and ended up using the describe_job_flows, terminate_job_flows API calls. The disturbing part is that the describe_job_flows documentation says that this call is deprecated and will be removed in the future. The trouble is that there doesn't seem to be an alternative unless the cluster_id and job_flow_id parameters are interchangeable or the same. Shedding some light on this would be very helpful in lieu of implementing what the CLI is doing.

**Comment by trevorrowe** [comment]
Thanks everyone for your feedback. I did speak with one of the CLI engineers and I am correct that these CLI commands are customizations. I'm passing this feedback to the EMR team. Currently there are no plans to implement these features in the AWS SDK for Ruby. Ideally these would be actual API calls eliminating the need to duplicate code logic between SDKs.
