### ISSUE TITLE
ECS should support waiters

### ISSUE THREAD

**Issue by ms-ati** [aws/aws-sdk-ruby#756]
It would be very helpful to support waiting on ECS operations:
    http://docs.aws.amazon.com/sdkforruby/api/Aws/ECS/Client.html#waiter_names-instance_method

For example, one must call deregister_container_instance in some cases, but there is no waiter to wait for that operation to complete.

**Comment by trevorrowe** [comment]
Thanks for submitting the feature request. I've added this as a feature request to our public backlog here: https://github.com/aws/aws-sdk-ruby/blob/master/FEATURE_REQUESTS.md#awsecsclient-waiters

**Comment by ms-ati** [comment]
Very cool, thanks for adding it to the list.

**Comment by euank** [comment]
@ms-ati 
Good news, there are some ECS waiters now :smiley:

I specifically added `:services_stable`, `:services_inactive`, `:tasks_running`, and `:tasks_stopped`. These are included in the recent `v2.1.1` release.

I did not add a waiter for `deregister_container_instance` because it's actually a synchronous operation.

If you have suggestions for other waiters, or run into issues with these, I'd be happy to look into it.
Cheers,
Euan

**Comment by ms-ati** [comment]
Sweet, thanks @euank I will try these out when I upgrade.
