### ISSUE TITLE
s3 bucket existence - unexpected behavior

### ISSUE THREAD

**Issue by s2t2** [aws/aws-sdk-ruby#796]
The code below demonstrates unexpected behavior when working with buckets in version 2.0.4.1. See also https://github.com/aws/aws-sdk-ruby/issues/460#issuecomment-97170675.

```` rb
creds = Aws::Credentials.new(KEY_ID, KEY_SECRET)

# A) CLIENT
client = Aws::S3::Client.new(:region => REGION, :credentials => creds)
bucket1 = Aws::S3::Bucket.new(:name => BUCKET_NAME, :client => client)
bucket1.exists? #> Aws::S3::Errors::Http301Error: from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.41/lib/aws-sdk-resources/resource.rb:134:in `rescue in exists?'
bucket1.create(:acl => "private") #> Aws::S3::Errors::BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

# B) RESOURCE
resource = Aws::S3::Resource.new(:region => REGION, credentials: creds)
bucket2 = resource.create_bucket(:bucket => BUCKET_NAME, :acl => "private")
bucket2.exists? #> true
````

**Comment by trevorrowe** [comment]
Thank you for reporting the issue. The `#exists?` check works by making a HEAD request to the bucket. Because we do not know the actual region of the bucket, that may not exist at all, the HEAD request is being sent to the currently configured region for the `Aws::S3::Client`.

It looks like Amazon S3 returns 301 permanent redirects for existing buckets when you head it in the wrong region. The fix would be to treat this status code as a successful check. Yes the bucket exists.

**Comment by trevorrowe** [comment]
The fix was very straight forward. I've added a test to cover regressions. This should go out later this week. Thank you for submitting the bug report and for your patience!
