### ISSUE TITLE
KMS Client-Side Encryption

### ISSUE THREAD

**Issue by samjdacanay** [aws/aws-sdk-ruby#811]
As mentioned in http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingClientSideEncryption.html, at least for JAVA, client-side encryption using a Key Management Service Customer Master Key ID is supported.

This would be some much appreciated functionality for the ruby sdk.

The Java documentation for this feature also includes a code snippet here: http://docs.aws.amazon.com/AmazonS3/latest/dev/client-side-using-kms-java.html, if this is useful for illustrating this feature request.

**Comment by gdanko** [comment]
I wonder if it is possible to create a KMS data key and use that to decrypt a file encrypted in Java:

dek = kms.generate_data_key(
    key_id: key_id,
    key_spec: "AES_256"
)

s3_enc = Aws::S3::Encryption::Client.new(
    client: s3,
    encryption_key: dek["plaintext"]
)

You are effectively providing a KMS key as your encryption_key. Maybe?

**Comment by trevorrowe** [comment]
Looking at the API reference documentation for [GenerateDataKey](http://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKey.html) it appears this API is meant for generating one-time use encryption keys. These keys should be used to encrypt data and then you store the encrypted data with the encrypted version of this key. You can then use your KMS key id to decrypt the data key later. This is very similar to the envelope encryption pattern used by the client side encryption. Unfortunately, it means this data key will not match that of the object. 

I think the best route here is to mimic Java's implementation of client-side encryption with KMS. I'm inclined to do this work, I'm just not sure when I'll be able to hop on this. I'm wrapping up some work on the 2.1 version of the SDK, and then I should be able to prioritize this.

I'd be happy thought to give assistance to anyone trying to work around this until a generalized implementation can be added. 

Basically you need to HEAD the object to get the encryption envelope. In the metadata of the object (the material description), it should contain the KMS key id used to encrypt the envelope. Pass the encrypted envelope and the kms key id to `Aws::KMS::Client#decrypt` and you will get back the actual key that was used to encrypt the object. Now you can create a decryption cipher. Stream data from your encrypted object from S3 through the cipher and you should finally have your object plaintext.

This shouldn't be too hard to cobble together. Its a bit more work to augment the existing encryption client to simply accept a KMS key id and to do all of this. Primarly because KMS does not ever return the master key (only its id). This means you have to use `#encrypt` and `#decrypt` via `Aws::KMS::Client`.

**Comment by trevorrowe** [comment]
I've pushed a work-in-progress branch of the SDK that adds support for client-side encryption with KMS.

https://github.com/aws/aws-sdk-ruby/tree/s3-cse-kms

Here is a quick example:

```ruby
s3 = Aws::S3::Encryption::Client.new(kms_key_id:'...')
s3.put_object(...)
s3.get_object(...)
```

**Comment by keviny22** [comment]
@trevorrowe I'm really interested in this feature being added. Anything I can do to help move this feature along?

**Comment by trevorrowe** [comment]
I've got a working implementation with tests now available in the s3-cse-kms. If you'd like to check it out and take it for a spin, it should be ready. Otherwise, I suspect that I will be shipping this with a release later this week.

**Comment by trevorrowe** [comment]
Sorry for the radio silence on this. This feature has been released, a few versions back actually. You should be able to update and use it now. Thanks for the patience.
