### ISSUE TITLE
SQS change message visibility timeout from QueuePoller

### ISSUE THREAD

**Issue by ianneub** [aws/aws-sdk-ruby#821]
Using aws-sdk 2.0.44.

I'm having trouble changing the message timeout using the helper provided by the QueuePoller class.

```
undefined method `change_message_visibility_timeout' for #<Aws::SQS::Client>

/usr/local/bundle/gems/aws-sdk-resources-2.0.43/lib/aws-sdk-resources/services/sqs/queue_poller.rb:349
```

https://github.com/aws/aws-sdk-ruby/blob/master/aws-sdk-resources/lib/aws-sdk-resources/services/sqs/queue_poller.rb#L349

**Comment by trevorrowe** [comment]
Thanks for reporting the issue. The fix was a one-liner. The tests did not correctly catch this because they were asserting the wrong operation name was to be called. I've updated the test to **not** assert a specific method is called. Instead, I allow the client to receive and respond and to assert on the response.

Sorry for the inconvenience. The fix for this should be released later this week.

**Comment by ianneub** [comment]
Wow, you're fast @trevorrowe ! Thanks for the fix!
