### ISSUE TITLE
ThrottlingException Rate exceeded

### ISSUE THREAD

**Issue by malachheb** [aws/aws-sdk-ruby#825]
when I exceed the amazon emr api limit, the method `AWS::EMR.new.job_flows.create()` throw a exception ` AWS::EMR::Errors::ThrottlingException Rate exceeded` but the job is created in amazon emr platform. it's a normal behaviour or an issue ?

**Comment by trevorrowe** [comment]
Are you positive it was that call that trigger the throttling error? If so, it surprises me that the job flow was still created. This would be problematic as the response from that API call is supposed to return the job flow id so that you can reference it later.

If you haven't done so, might I recommend posting your question in the EMR forums?
https://forums.aws.amazon.com/forum.jspa?forumID=52

**Comment by trevorrowe** [comment]
Closing stale issue. Without additional information I wouldn't be able to help debug this. Please re-open if you see this again or have more context.
