### ISSUE TITLE
No documentation to delete bucket policies in v1

### ISSUE THREAD

**Issue by rspencer01** [aws/aws-sdk-ruby#852]
In the v1 SDK, the functionality of 

    bucket.policy.delete

is not documented.  The code of interest is at 
https://github.com/aws/aws-sdk-ruby/blob/aws-sdk-v1/lib/aws/s3/bucket.rb#L590

**Comment by awood45** [comment]
Thanks for bringing this to our attention.

V1 of the SDK is approaching end of life, and we are unlikely to do further releases except in the case of critical issues. Because of that, I'm closing this issue without applying a patch.

If you have any questions or confusion about that method, feel free to reopen and ask.
