### ISSUE TITLE
Status for VPC Internet Gateway

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#856]
The state of an internet gateway attachment is being returned by the SDK as 'available'. The valid states per the docs are attaching | attached | detaching | detached

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InternetGatewayAttachment.html

I have an attached gateway that is 'available' per the API call with the latest version of the SDK. The EC2 console displays the status as 'attached'. Should we follow the API or the docs? Or does the available status of the attachment actually mean that a gateway is attached to a VPC and is available for traffic?

```Ruby
ec2.describe_internet_gateways

#<struct Aws::EC2::Types::InternetGateway internet_gateway_id="igw-5d558831", 
attachments=[#<struct Aws::EC2::Types::InternetGatewayAttachment 
vpc_id="vpc-fcd36369", state="available">], tags=[]>

```

**Comment by pchaganti** [comment]
After experimenting with this, when the API returns 'available' for the attachment state, the EC2 console displays status of the gateway as attached to VPC. 

When the API returns a blank string for the attachment state, the EC2 console displays the status as detached.

**Comment by trevorrowe** [comment]
The SDK does not modify the values returned from Amazon EC2. I suspect there are some deficiencies in the API reference documentation, hence the discrepancy. I'll raise this issue upstream with the EC2 team. We intentionally do not add client-side modifications to the API results to ensure forwards compatibility with API updates. In the case of the console, they have additional business logic built into the web application.

If attach a gateway and it is still showing state as "available", I suspect it is just an eventual consistency issue. Has the status since updated?

**Comment by pchaganti** [comment]
The status still shows as available. This might be a doc discrepancy.

**Comment by trevorrowe** [comment]
This is very likely an issue with the documentation.  I can pass this along to the documentation team.

**Comment by pchaganti** [comment]
Thanks!

**Comment by voy** [comment]
I have stumbled upon the very same thing using the Java SDK. The api is returning "available", while the AttachmentStatus enum only knows attaching/detaching/attached/detached. It is strange, I ended up just using my own "available" string constant.
