### ISSUE TITLE
AWS SDK v1's ruby 1.8.7 support

### ISSUE THREAD

**Issue by cliffano** [aws/aws-sdk-ruby#877]
Is AWS SDK v1 still meant to support ruby 1.8.7 when the latest nokogiri requires ruby >= 1.9.2 ?

AWS SDK v1 documentation http://docs.aws.amazon.com/AWSSdkDocsRuby/latest/DeveloperGuide/ruby-dg-install-sdk.html mentions that "The AWS Ruby SDK runs on Ruby 1.8.7 and later versions."

However, the dependency requirement for nokogiri is >= 1.4.4, which actually breaks AWS SDK v1 installation on ruby 1.8.7 because nokogiri deprecated ruby 1.8.7 support since 22/04/2013 https://github.com/sparklemotion/nokogiri/commit/7c5f3f6c444b73192abbcc19ef9e3c987cdf7ab0#diff-52c976fc38ed2b4e3b1192f8a8e24cff

[uproot@megaman]# ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
[uproot@megaman]# gem --version
1.3.7
[uproot@megaman]# gem install aws-sdk-v1
ERROR:  Error installing aws-sdk-v1:
        nokogiri requires Ruby version >= 1.9.2.

**Comment by awood45** [comment]
We go into more depth in a blog post here: https://ruby.awsblog.com/post/Tx2T9MFQJK7U74N/AWS-SDK-for-Ruby-and-Nokogiri

The short version is that you need to specify a Gemfile.lock for 1.8.7 support, as we made the decision to remove our own lock so that Ruby 1.9+ users could roll Nokogiri forward after 1.8.7 support was dropped by the Ruby core team.

Feel free to reopen if anything in the post doesn't work for you.

**Comment by cliffano** [comment]
Thanks @awood45 , understood the reasoning.
