### ISSUE TITLE
Aws::OpsWorks::Types::DescribeStacksResult no longer Enumerable?

### ISSUE THREAD

**Issue by albertsj1** [aws/aws-sdk-ruby#885]
I've seen a couple other issues about Enumerable missing from some objects.  I upgraded aws-sdk-core from 2.0.8 to 2.1.7 and noticed that I'm no longer able to run describe_stacks.each.

I get the following error message:
```
NoMethodError: undefined method `each' for #<Aws::OpsWorks::Types::DescribeStacksResult:0x007faf85b2f7f0>
```

**Comment by trevorrowe** [comment]
There was an intentional change made to response paging with version 2.1. Prior to version 2.1 every operation was incorrectly decorated as a pageable response. This behavior however was buggy and could cause silent failures.

For response paging to work, there is some minimal configuration that indicates when results are truncated, and how to make a follow-up request to get more results. When this configuration is not present, then the pre-2.1 pager would simply say, I got all of the results. AWS services are frequently adding new operations and if the paging tokens were not added for a new operation, it would incorrectly report that all results were received in the first response and fail to get the rest.

For this reason, in 2.1+ a response will only be decorated with paging methods, such as `#each` when the configuration is present. This means users upgrading that were previously calling a pageable API call that did not have its configuration would receive a `NoMethodError`. Helps identify operations missing their configuration and it also means operations that should never be paged, like a PUT object to Amazon S3, will ever have the extra methods.

That said, I am unable to reproduce your issue. I checked and there is configuration for the DescribeStacks call. Here is the code that I ran to test this:

```ruby
opsworks = Aws::OpsWorks::Client.new
opsworks.describe_stacks.each do |page|
  # ...
end
```

Can you share the code you are running that produces this error?

**Comment by albertsj1** [comment]
I just did some testing with different versions and my code was working with version 2.0.48, but stopped working with 2.1.0 release.
Checking the changelog, I can see that 2.1.0 introduced backward breaking changes for paging responses.  Closing this issue since it's an intentional code change that requires me to modify my code.

**Comment by albertsj1** [comment]
@trevorrowe 
Sorry. Saw your comment after I submitted my comment.  I had the window open for an hour before clicking the comment button. oops.
Anyway, thanks for the detailed explanation.  Let me look deeper at my code and confirm the problem and I'll reply back.
Thanks again.
