### ISSUE TITLE
Clarify client/server errors?

### ISSUE THREAD

**Issue by mockdeep** [aws/aws-sdk-ruby#888]
We got an `AWS::Errors::Base` thrown in our app today. It's hard to tell from the stack trace why it happened:

```
 [GEM_ROOT]/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:375 :in `return_or_raise`
[GEM_ROOT]/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:476 :in `client_request`
(eval):3 :in `get_object`
[GEM_ROOT]/gems/aws-sdk-v1-1.64.0/lib/aws/s3/s3_object.rb:1371 :in `get_object`
[GEM_ROOT]/gems/aws-sdk-v1-1.64.0/lib/aws/s3/s3_object.rb:1090 :in `read`
[GEM_ROOT]/gems/carrierwave-aws-0.7.0/lib/carrierwave/storage/aws_file.rb:40 :in `read` 
```

My best guess is that it's a throttling error, since it only happened once and everything seems to be working fine otherwise, but it would be nice for these to throw more specific errors so we can get a better sense of how to respond.

**Comment by trevorrowe** [comment]
The SDK will throw a generic error such as this when it is not possible to extract the normal error code from the http response. This can happen for a handful of reasons. The most common reason is the body was not available or was corrupted. This can happen for responses to HEAD requests that don't have bodies or due to transient networking issues.

If you continue to see these errors, please feel free to share more details and we'll see if the SDK should be doing more in this instance.
