### ISSUE TITLE
Is it possible to change Ruby AWS SDK to generate V2 signature pre-signed URL? 

### ISSUE THREAD

**Issue by hrchu** [aws/aws-sdk-ruby#921]
I tried configure "signature_version" to "s3" when new a s3 client, like
signer = Aws::S3::Presigner.new(client:Aws::S3::Client.new(region: "ap-northeast-1",signature_version: 's3'))

but no used, I still get V4 signature url. I checked source code "presigner.rb", looks like it can only generate v4 signature. 
Is there any possible to generate v2 signature??

**Comment by trevorrowe** [comment]
You can use the version 1 SDK, `aws-sdk-v1` to generate v2 signatures. It uses a different gem name and module, so you can use them in the same application. Version 2 of the AWS SDK for Ruby intentionally does not provide a v2 pre-signed URL functionality. There are an increasing number of scenarios where these signatures will not work due to restrictions on new regions, server side encryption requirements, and more.

**Comment by trevorrowe** [comment]
Closing this question as a non-issue for now. Please re-open if there is an issue with the v4 signatures.

**Comment by rob-murray** [comment]
This is misleading as there are references to being able to configure the signer with `signature_version: 's3'` - I cannot see any notice saying this is being removed.

https://github.com/aws/aws-sdk-ruby/releases/tag/v2.2.0

This is useful as I need to provide the presigned url to a mobile client I have no control over.

**Comment by awood45** [comment]
The signature version hasn't been removed (the defaults and s3 signer error handling logic have, more details in `UPGRADING.md`).

The presigner in V2 of the SDK has always used Signature Version 4. As Trevor indicated, it would be difficult to properly support signature versions other than 4 for presigned URLs.
