### ISSUE TITLE
Aws::AutoScaling::Errors::ValidationError - UserData does not appear to be base64 encoded:

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-sdk-ruby#922]
Getting this error when creating a launch configuration. The requirement to base64 encode userdata when creating a launch config is not in the API docs - http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_CreateLaunchConfiguration.html

We want the userdata to be available to the instance as plain text. Are we reading this right?

thanks!

**Comment by trevorrowe** [comment]
EC2 requires the user data to be base64 encoded when sent over the wire. This does not affect the format it is made available in on the instance. This simply ensures it is safely encoded for the request. I suspect that AutoScaling is simply passing this requirement on. The SDK automatically base64 encodes data when using the EC2 API as part of the protocol. If AutoScaling had described this parameter as a binary value instead of string then we would have managed this over the wire as well.

At this point, I'm not sure there is much we can do. I would prefer if the SDK did this automatically as it does for EC2, but changing this now would be a breaking change for existing customers.

**Comment by pchaganti** [comment]
Got it. Thx for the clarification!
