### ISSUE TITLE
S3::Object#copy_from/copy_to does not set explicitly specified content_type

### ISSUE THREAD

**Issue by toaster** [aws/aws-sdk-ruby#946]
Given two `S3::Object`: `src_object` and `dest_object`:

```ruby
> src_object.put(body: "foobar", content_type: "text/html")
=> #<struct Aws::S3::Types::PutObjectOutput … >
> src_object.get.content_type
=> "text/html"
> dest_object.copy_from(src_object, content_type: "application/zip")
=> #<struct Aws::S3::Types::CopyObjectOutput … >
> dest_object.get.content_type
=> "text/html"
```

The same happens when using `copy_from`. This is a regression against v1 and currently an issue blocking us switching to v2. Sadly we need v2 since `#copy_from` (hopefully) supports multipart copy there.

**Comment by trevorrowe** [comment]
The default behavior for a copy object operation in Amazon S3 is to copy all of the metadata from the source object to the target object.  Metadata, such as content-type, content-encoding, the ACL (access control list), user-supplied metadata, etc are all ignored unless by S3 unless you set a special header, `x-amz-metadata-directive: REPLACE`.  

The version 1 SDK inspects incoming options and attempts to decide if any options that would modify object metadata are present, and if so, would attempt a smart copy. This works for many cases, but proved to be a leaky abstract. First, an extra request is necessary to HEAD the object so that metadata not given in the copy could be maintained and not lost. Unfortunately, this didn't extend to all object metadata. HEAD object did not previously return the storage class, and it also does not return the ACL. If is the SDK performed the HEAD and GET Object ACL requests, Amazon S3 could add other metadata, that require other API calls in the future and then these would be silently dropped.

To avoid surprising behavior, we chose not do have the smart copy in version 2. You can modify the metadata for an object, but you must set `metadata_directive: 'REPLACE'`, in your call to `#copy_from`. This preserves the S3 behavior. This does mean if you want to only change the content-type but you also want to preserve the object ACL, or user metadata, you either need to know those values and supply them to `#copy_from` or you need to HEAD and GET Object ACL yourself.

Currently there are no plans to port the smart copy behavior forward. We received many bug reports over the years for this functionality and it remains incomplete today.

**Comment by trevorrowe** [comment]
Oh, and here is an example of what you need:

```ruby
source = Aws::S3::Object.new('aws-sdk', 'source')
target = Aws::S3::Object.new('aws-sdk', 'target')
source.put(body:'text', content_type: 'text/plain')
target.copy_from(source, content_type: 'application/json', metadata_directive: 'REPLACE')
target.content_type
#=> 'application/json'
```

**Comment by trevorrowe** [comment]
I'm closing this as a non-issue, but please feel free to continue the discussion. I'm open to alternative ideas or view points. Feel free to re-open if you run into any issues.

**Comment by toaster** [comment]
Thanks for the clarification.

**Comment by lbrito1** [comment]
@trevorrowe I'm wondering whether this behavior applies to `copy_to` as well:

> Metadata, such as content-type, content-encoding, the ACL (access control list), user-supplied metadata, etc are all ignored unless by S3 unless you set a special header, x-amz-metadata-directive: REPLACE.

I have some v1 legacy code which is being updated to v2, and I have a `copy_to` with a few extra options. In v2, options `:content_type` and `:acl` now raise `Aws::S3::Errors::InvalidArgument: ` (blank at the end) errors. Code section looks like this:

```
.copy_to(obj.key,
  cache_control: "max-age=123456",
  expires: some_date.httpdate,
  acl: :public_read,
  content_type: obj.get.content_type
)
```

Is this expected? Are these options no longer valid or required?
