### ISSUE TITLE
http_proxy is ignored

### ISSUE THREAD

**Issue by lox** [aws/aws-sdk-ruby#956]
Whilst trying to solve https://github.com/99designs/aws-vault/issues/40 I noticed that aws-sdk-ruby intentionally ignores system proxies. 

https://github.com/aws/aws-sdk-ruby/commit/5af5b8dc19bed46d029e257308305c959acff56c

What's the rationale? It's different behaviour from the other SDK's that I have looked at.

**Comment by trevorrowe** [comment]
To be honest, I don't recall the motivation for ignoring system proxies. Changing this at this point would possibly cause other problems, as some issue likely prompted the change.

I suspect there are valid cases for using the system proxy to contact the instance metadata service and other times where using the system proxy is undesirable or problematic. The problem here is the SDK does not give the user any control over when to use or when to ignore the system proxy.

Would it be sufficient if `AWS::Core::CredentialProviders::EC2Provider#initialize` accepted a `:http_proxy` option?

**Comment by trevorrowe** [comment]
I also did some additional digging. The Ruby SDK is not the only SDK that disables environment proxies when connecting to the instance metadata service. I spoke with one of the CLI engineers and they do the same thing.

**Comment by trevorrowe** [comment]
I'm going to move this to our feature requests.  Please feel free to continue commenting on this issue.
