### ISSUE TITLE
Documentation for Aws::S3::Errors::BucketAlreadyOwnedByYou

### ISSUE THREAD

**Issue by keviny22** [aws/aws-sdk-ruby#967]
This issue is to update the documentation.

When trying to create a bucket that i already created in us-west-2 I get the following error. 

Aws::S3::Errors::BucketAlreadyOwnedByYou Your previous request to create the named bucket succeeded and you already own it.

The Error isn't documented here http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Errors.html so i was  rescuing on BucketAlreadyExists which is the error i thought i would see.

**Comment by awood45** [comment]
I'll look in to this.

**Comment by awood45** [comment]
So, I think it's safe for you to catch both - there's a small semantic difference, in that BucketAlreadyOwnedByYou only occurs when you're trying to create a bucket that exists && is yours, unlike the other error which is for bucket names otherwise taken.

I'll work on the documentation update in the meantime, because I agree that could be spelled out in the docs for clarity.

**Comment by trevorrowe** [comment]
I've sent a contribution up-stream. It appears this error is only raised when you attempt to create a bucket you already own outside of the classic (us-east-1) region. This will be pulled in with our next S3 update.
