### ISSUE TITLE
 Aws::EC2::Client#describe_images is painfully slow

### ISSUE THREAD

**Issue by vemv** [aws/aws-sdk-ruby#989]
Hi,

I've been using various Client classes for a while (EC2, AutoScaling, ELB, IAM) and they all work quickly, correctly with the same exact, super-simple configuration (they just pick up my credentials from `ENV`).

`Aws::EC2::Client#describe_images` takes a lot of time to load though, in fact for weeks I thought it just hanged forever - but now I just found out it eventually gets the result:

`#<Benchmark::Tms:0x007fc705d20478 @cstime=0.0, @cutime=0.0, @label="", @real=75.7291319599999, @stime=0.73, @total=24.470000000000002, @utime=23.740000000000002>`

I have only 3 AMIs in the AWS account I'm querying.

Using 2.1.35.

Don't know if this is a AWS or sdk issue, it seems to me that it should be addressed in any case.

Cheers - Victor

**Comment by vemv** [comment]
Ahhh I just realised that by default (and kinda reasonably), describe_images fetches all kind of images, not just mine. Retrieving 35754 objects certainly takes time!

As I said, this slowness-by default was so high that I thought `describe_images` didn't work at all. Some change ought to be performed - current behavior is not very friendly.

Keep in mind that `describe_images` is different from most other methods (e.g. `Aws::AutoScaling::Client#describe_launch_configurations`), because in most other methods is safe to asume that _my_ objects will be returned.

This seems solvable by:

* Print a warning if no filters were passed
* Put a small request size if no filters were passed (i.e. ask for 100 AMIs instead of 35754)
* Defaulting to describe my images only.

**Comment by awood45** [comment]
I don't think printing a warning when no filters are passed is appropriate, because in some cases that's exactly what the caller is intending to do.

Similarly, while you have the ability to filter in a way that only describes your images using the `owners: ["self"]` option, changing the default behavior in any way is a backwards incompatible change, a customization, and produces behavior contrary to what the documentation describes.

I can forward your feedback to the Amazon EC2 team, but I don't see a change here that I can make. I'd recommend using the available filters to help constrain the size of the response to your calls.

**Comment by vemv** [comment]
I understand.

Would changing the default requested pagination size also be considered a breaking change?

**Comment by awood45** [comment]
I don't see an option within the API to do that. I can give feedback to the Amazon EC2 team, but from a client perspective there's not much to be done.
